#! /bin/sh
echo "*************************************************************"
echo "Author:Wencai Yi"
echo "Email:yi.wencai@163.com  Qufu Normal University"
echo "Function: A program that can be used to build Moire supperlattice with POSCAR"
echo "Version:1.1"
echo "First released time: 2022.01.02"
echo "Last modified time: 2022.01.15 by Wencai Yi"
echo "Thanks JunLuo for the code of building heterojunction "
echo "*************************************************************"


## check wether exit python3
test=`which python3 2> /dev/null`
if [ -z $test ]; then
 echo "There is no python3, please running this command under python3 environment!"
 echo "We suggest that you install anaconda3 in your machine!"
 exit;
fi

if [ $# -lt 1 ];then
 echo "Please use: qvasp -mos subs1 (subs1 should be two dimensional material in POSCAR format),stop"
 exit;
fi

if [ -e $1 ];then
 continue;
else
 echo "The file of $1 not exist,stop"
 exit;
fi


cp $1 POSCAR
echo 602 | $qvasppath/exefile/Tools/USERTooLs/vaspkit | grep 123
echo "The target file has been converted into primitive cell!"
### checking PRIMCELL.vasp
mv PRIMCELL.vasp POSCAR
$qvasppath/exefile/Tools/2d-center.x
cp POSCAR_center POSCAR1
cp POSCAR1 POSCAR2

#python3 $qvasppath/exefile/Tools/find_moires.py
$qvasppath/exefile/Tools/find_moires.x
########### deal repeat  #################
$qvasppath/exefile/Tools/sort-moires.x
sh $qvasppath/exefile/Tools/redine_POSCAR.sh

## clean
#rm  heter.in POSCAR1 POSCAR2 POSCAR22 POSCAR11 POSCAR sorted_by_atomic_number.txt

echo " "
echo "Cite with \"The calculations were assisted by the qvasp and vaspkit [1-2]\"  "
echo "[1] Wencai Yi, et al.qvasp: A Flexible Toolkit for VASP Users in Materials Simulations"
echo "[2] Vei WANG, et al. VASPKIT: A user-friendly interface facilitating high-throughput computing and analysis using VASP code"
