#!/usr/bin/env python
# @Time : 2024/5/31 11:24
# @Author : Naixiang Yan
# Modified by : Wencai Yi
from __future__ import division
import numpy as np

def read_poscar(filename='POSCAR'):
    
    result = {}
    
    with open(filename, 'r') as f:
        lines = f.readlines()
    
    result['title'] = lines[0].strip()
    
    result['scale'] = float(lines[1].strip())
    
    lattice = []
    for i in range(2, 5):
        lattice.append([float(x) for x in lines[i].strip().split()])
    result['lattice'] = np.array(lattice)
    
    atom_types = lines[5].strip().split()
    result['atom_types'] = atom_types
    
    atom_numbers = [int(x) for x in lines[6].strip().split()]
    result['atom_numbers'] = atom_numbers
    result['total_atoms'] = sum(atom_numbers)
    
    line_idx = 7
    coordinate_type = lines[line_idx].strip().upper()
    result['coordinate_type'] = coordinate_type
    
    selective_dynamics = False
    if coordinate_type in ['SEL', 'SELECTIVE']:
        selective_dynamics = True
        coordinate_type = lines[line_idx+1].strip().upper()
        result['coordinate_type'] = coordinate_type
        line_idx += 1
    
    positions = []
    if selective_dynamics:
        for i in range(line_idx+1, line_idx+1+result['total_atoms']):
            parts = lines[i].strip().split()
            positions.append([float(x) for x in parts[:3]])
    else:
        for i in range(line_idx+1, line_idx+1+result['total_atoms']):
            parts = lines[i].strip().split()
            positions.append([float(x) for x in parts[:3]])
    
    result['positions'] = np.array(positions)
    
    if selective_dynamics:
        selective_flags = []
        for i in range(line_idx+1, line_idx+1+result['total_atoms']):
            parts = lines[i].strip().split()
            flags = [x.upper() == 'T' for x in parts[3:6]]
            selective_flags.append(flags)
        result['selective_dynamics'] = np.array(selective_flags)
    
    if len(lines) > line_idx + result['total_atoms'] + 1:
        velocities = []
        for i in range(line_idx + result['total_atoms'] + 1, len(lines)):
            parts = lines[i].strip().split()
            if not parts:
                continue
            velocities.append([float(x) for x in parts[:3]])
        if velocities:
            result['velocities'] = np.array(velocities)
    
    return result

def write_poscar(structure_data, filename='POSCAR_redlatt', direct=True):

    try:
        with open(filename, 'w') as f:
            f.write("%s\n" % structure_data.get('title', 'Generated by Python'))
            
            f.write("%.10f\n" % structure_data.get('scale', 1.0))
            
            lattice = structure_data.get('lattice', np.eye(3))
            for vec in lattice:
                f.write(" %20.16f %20.16f %20.16f\n" % (vec[0], vec[1], vec[2]))
            
            atom_types = structure_data.get('atom_types', ['X'])
            f.write(' '.join(atom_types) + '\n')
            
            atom_numbers = structure_data.get('atom_numbers', [1])
            f.write(' '.join([str(n) for n in atom_numbers]) + '\n')
            
            if direct:
                f.write('Direct\n')
            else:
                f.write('Cartesian\n')
            
            positions = structure_data.get('positions', np.zeros((sum(atom_numbers), 3)))
            
            if 'selective_dynamics' in structure_data:
                selective_flags = structure_data['selective_dynamics']
                for i, pos in enumerate(positions):
                    flags = ['T' if f else 'F' for f in selective_flags[i]]
                    f.write(" %20.16f %20.16f %20.16f %s\n" % (pos[0], pos[1], pos[2], ' '.join(flags)))
            else:
                for pos in positions:
                    f.write(" %20.16f %20.16f %20.16f\n" % (pos[0], pos[1], pos[2]))
            
            if 'velocities' in structure_data:
                f.write('Selective dynamics\n')
                if direct:
                    f.write('Direct\n')
                else:
                    f.write('Cartesian\n')
                
                velocities = structure_data['velocities']
                for vel in velocities:
                    f.write(" %20.16f %20.16f %20.16f\n" % (vel[0], vel[1], vel[2]))
            
        return True
    except Exception as e:
        return False

if __name__ == "__main__":

   poscar_data = read_poscar('POSCAR')
   #for i, vec in enumerate(poscar_data['lattice']):
   #     n1 =  {vec}
   ls1 = poscar_data['lattice'][0]     
   ls2 = poscar_data['lattice'][1]     
   ls3 = poscar_data['lattice'][2]     
   #print(n1)
   #print(n2)
   #print(n3)
   #n1 = raw_input("Input the lattice constant with 3X3 matrix:\n")
   #n2 = raw_input()
   #n3 = raw_input()
   #ls1 = [float(i) for i in n1.split()]
   #ls2 = [float(i) for i in n2.split()]
   #ls3 = [float(i) for i in n3.split()]

   alllist = [ls1, ls2, ls3]
   latt = np.array(alllist)

   n1 = raw_input("\nDefine the atomic coodinate of center:")
   n2 = raw_input("Define the atomic coodinate along x direction:")
   n3 = raw_input("Define the atomic coodinate along z direction:")
   ls1 = [float(i) for i in n1.split()]
   ls2 = [float(i) for i in n2.split()]
   ls3 = [float(i) for i in n3.split()]

   o = np.array(ls1)
   x = np.array(ls2)
   z = np.array(ls3)

   z = z - o
   x = x - o
   z = np.matmul(z, latt)
   x = np.matmul(x, latt)
   z = z / np.linalg.norm(z)
   x = x / np.linalg.norm(x)
   y = np.cross(z, x)
   y = y / np.linalg.norm(y)
   x = np.cross(y, z)
   tran = np.array([x, y, z])
   new_latt = np.matmul(latt, np.linalg.inv(tran))

   print('\nThe new lattice constants are:')
   for row in new_latt:
       print(' '.join(map(str, row)))

   
   poscar_data['lattice'][0] = new_latt[0]
   poscar_data['lattice'][1] = new_latt[1]
   poscar_data['lattice'][2] = new_latt[2]

   success = write_poscar(poscar_data, 'POSCAR_redlatt')
    
   if success:
       print('\nThe new lattice constants are written in POSCAR_redlatt.\n')
   else:
       print("\nFailed, check the POSCAR.\n")
   #for row in new_latt:
   #    print(' '.join(map(str,row)))
   #print(poscar_data['lattice'][0])

# 3.3782863617 0.0000000000 0.0000000000
# -1.6891435704 2.9256815856 0.0000000000
# 0.0000000000 0.0000000000 6.9528589249
