"""
Third pass: translate all remaining Chinese text.
Covers comments, docstrings, log messages, print statements, f-strings.
"""
import re
from pathlib import Path

BASE = Path(__file__).parent

REPLACEMENTS = [
    # ---- log levels remaining ----
    ('"失败"', '"FAIL"'), ('"成功"', '"SUCCESS"'),
    # ---- remaining region names ----
    ('elif region == "top20%" or region == "顶部":', 'elif region == "top20%" or region == "top":'),
    ('elif region == "中间50%":', 'elif region == "middle50%":'),
    ('elif region == "全图":', 'elif region == "full-image":'),
    ('elif region == "去底30%去左20%":  # 去底30% 去左20%', 'elif region == "no-bottom30%-no-left20%":  # remove bottom 30% and left 20%'),
    ('elif region == "右上角":', 'elif region == "top-right":'),
    ('elif region == "右侧":', 'elif region == "right":'),
    ('elif region == "左侧":', 'elif region == "left":'),
    ('else:  # 全图', 'else:  # full image'),
    ('else:  # 完整', 'else:  # full'),
    ('if region == "bottom20%" or region == "底部":', 'if region == "bottom20%" or region == "bottom":'),
    # ---- docstrings ----
    ('"""从OCR文本中提取文件名 - 增强版（优先从方括号提取）"""',
     '"""Extract filename from OCR text - enhanced version (prefer bracket extraction)"""'),
    # ---- comment blocks ----
    ('# --- 3. 如果遍历完都没有返回，说明失败 ---', '# --- 3. If loop completes without returning, it is a failure ---'),
    ('# --- A. 常规模式检测 (Normal State) ---', '# --- A. Normal mode detection (Normal State) ---'),
    ('# --- A. 标题匹配逻辑 (支持重复) ---', '# --- A. Title matching logic (supports duplicates) ---'),
    ('# --- A. 检查当前帧的文件匹配情况 ---', '# --- A. Check file match for current frame ---'),
    ('# --- B. 坐标轴标签严格统计 ---', '# --- B. Strict axis label count ---'),
    ('# --- B. 堆叠模式检测 (Stacked State) ---', '# --- B. Stacked mode detection (Stacked State) ---'),
    ('# --- B. 文件全齐了！现在检查当前帧的 Binding Energy ---', '# --- B. All files matched! Now check Binding Energy in current frame ---'),
    ('# --- C. 最终判定 ---', '# --- C. Final decision ---'),
    ('# --- C. 最终判定：必须严格相等 ---', '# --- C. Final decision: must be strictly equal ---'),
    ('# --- 内部归一化辅助函数 ---', '# --- Internal normalization helper function ---'),
    ('# --- 步骤 1: 文本检测 (同时匹配 Zoom In 和 Step 数值) ---', '# --- Step 1: Text detection (match both Zoom In and Step value) ---'),
    ('# --- 步骤 2: 视觉相似度比较 (兜底方案) ---', '# --- Step 2: Visual similarity comparison (fallback) ---'),
    ("# ... (其他策略省略，保持原有逻辑)", "# ... (other strategies omitted, keep original logic)"),
    ('# 1. 准备期望文件的规范化映射', '# 1. Prepare normalized mapping for expected files'),
    ('# 1. 定义匹配模式', '# 1. Define match patterns'),
    ('# 1. 构建并归一化所有待检测的目标集合', '# 1. Build and normalize all target sets for detection'),
    ('# 1. 检测 "zoom in"', '# 1. Detect "zoom in"'),
    ('# 1. 没有任何大数值特征 (sci, int, custom 均为 False)', '# 1. No large-value features at all (sci, int, custom all False)'),
    ('# 2. 核心正则：匹配带连字符的结构 [原子]-[原子]', '# 2. Core regex: match hyphenated structure [atom]-[atom]'),
    ('# 2. 检测 Step 数值 (例如 Step (%): 100)', '# 2. Detect Step value (e.g. Step (%): 100)'),
    ('# 2. 至少识别到 2 个小刻度数字', '# 2. At least 2 small tick numbers identified'),
    ('# 2. 遍历每一帧（每一个步骤）', '# 2. Iterate over every frame (every step)'),
    ('# 3. 对 OCR 识别到的原始文本进行归一化', '# 3. Normalize the raw OCR-recognized text'),
    ('# 4. 逻辑判定', '# 4. Logic decision'),
    ('# 4个角点的颜色是否一致', '# Check if all 4 corner colors are consistent'),
    ('# KEY: 规范化后的标准文件名 -> VALUE: [OCR可能识别的变体]', '# KEY: normalized standard filename -> VALUE: [possible OCR variants]'),
    ('# Normalize text用于更宽松的匹配', '# Normalize text for looser matching'),
    ('# 保存左侧面板', '# Save left panel'),
    ('# 创建裁剪图片缓存目录（用于视觉相似度比较）', '# Create cropped image cache directory (for visual similarity comparison)'),
    ('# 匹配 4位及以上的大整数 (如 40000, 10000, 2000)', '# Match 4+ digit large integers (e.g. 40000, 10000, 2000)'),
    ('# 匹配科学计数法 (如 1.20e5)', '# Match scientific notation (e.g. 1.20e5)'),
    ('# 只有"找到了必须关键词 且 没找到任何禁止关键词"才算通过', '# Only pass when "required keywords found AND no forbidden keywords found"'),
    ('# 只有当 出现过对话框、识别到Smart文本、且对话框已关闭时，才给满分', '# Only full score when: dialog appeared, Smart text recognized, and dialog closed'),
    ('# 只有当标题数量完全达标时，才进行坐标轴 OCR 深度检查', '# Only do axis OCR deep check when title count is fully met'),
    ('# 只检查参数名是否存在', '# Only check if parameter name exists'),
    ('# 处理expected_value', '# Process expected_value'),
    ('# 处理单个文件或多个文件', '# Handle single or multiple files'),
    ('# 如果当前帧匹配的文件数量比之前的记录多，更新"最佳记录"以便调试', '# If current frame matched more files than previous record, update "best record" for debugging'),
    ('# 提取这行中的所有数字（可能包含负数和小数）', '# Extract all numbers from this line (may include negatives and decimals)'),
    ('# 提高最小长度要求到4个字符', '# Raise minimum length requirement to 4 characters'),
    ("# 提高阈值，避免'stick' in 'ball-stick'", "# Raise threshold to avoid 'stick' in 'ball-stick'"),
    ('# 支持多种格式: "Width: 2000", "Width 2000", "Width=2000"', '# Support multiple formats: "Width: 2000", "Width 2000", "Width=2000"'),
    ('# 支持格式：x_min, x_max, y_min, y_max, z_min, z_max', '# Supported formats: x_min, x_max, y_min, y_max, z_min, z_max'),
    ('# 收集候选角点', '# Collect candidate corners'),
    ('# 收集够3个坐标就停止', '# Stop after collecting 3 coordinates'),
    ('# 收集角点信息', '# Collect corner info'),
    ('# 放大图像提高识别率', '# Enlarge image to improve recognition rate'),
    ('# 放大图像', '# Enlarge image'),
    ('# 文件名相同 且 轨迹中已标记导入', '# Same filename AND marked as imported in trajectory'),
    ('# 文件齐了 AND 能量标签数量也齐了 (>= 是为了防止 OCR 误读多出几个，通常 == 即可，这里用 == 严格匹配)', '# Files all matched AND energy label count also matched (>= to handle OCR over-reading, == is strict)'),
    ('# 文件齐了但 Binding Energy 不对，记录一下这种情况', '# Files matched but Binding Energy count wrong, record this case'),
    ('# 方式1: 关键词在文本中', '# Method 1: keyword in text'),
    ('# 方式2: 文本在关键词中', '# Method 2: text in keyword'),
    ('# 方法1: 完全匹配', '# Method 1: full match'),
    ('# 方法1: 完全匹配operations', '# Method 1: full match operations'),
    ('# 方法1: 精确匹配', '# Method 1: exact match'),
    ('# 方法2: 如果精确匹配失败，尝试容错匹配（允许 OCR 误差）', '# Method 2: if exact match fails, try fault-tolerant matching (allow OCR errors)'),
    ('# 方法2: 子串匹配operations (处理连字符等变体)', '# Method 2: substring match operations (handle hyphen variants etc.)'),
    ('# 方法3: 检查 opened_file (不要添加3D atomistic等自动生成的内容)', '# Method 3: check opened_file (do not add auto-generated content like 3D atomistic)'),
    ('# 方法：必须是精确匹配原子符号（如 "Na" 或 "Cl"），而不是标签（Na0, Cl1）', '# Method: must exactly match atom symbol (e.g. "Na" or "Cl"), not labels (Na0, Cl1)'),
    ('# 无@符号', '# No @ symbol'),
    ('# 无字段名: 直接检查value', '# No field name: check value directly'),
    ('# 无空格', '# No spaces'),
    ('# 映射对话框标题到操作', '# Map dialog title to operation'),
    ('# 显示前3个检测到的项', '# Show first 3 detected items'),
    ('# 晶面行号通常从 2 开始（1 可能是默认的）', '# Crystal plane row index usually starts from 2 (1 may be the default)'),
    ('# 更新调试用的最佳记录', '# Update best record for debugging'),
    ('# 替换可能被误识别的字符', '# Replace characters that may be misrecognized'),
    ('# 替换常见误识别字符', '# Replace common misrecognized characters'),
    ('# 最终判断', '# Final decision'),
    ('# 最终结果', '# Final result'),
    ('# 有字段名: 生成可能的操作名', '# Has field name: generate possible operation names'),
    ('# 有键状态（输入框 + 表格）', '# Bond state (input box + table)'),
    ('# 未找到弹窗', '# Dialog not found'),
    ('# 未通过的原因总结', '# Summary of failure reasons'),
    ('# 构建所有可能的文件组合', '# Build all possible file combinations'),
    ('# 构建所有可能的期望值列表', '# Build all possible expected value lists'),
    ('# 构建操作标识', '# Build operation identifier'),
    ('# 查找 Rows 和 Columns 设置', '# Find Rows and Columns settings'),
    ('# 查找normalized_text中包含哪个变体', '# Find which variant is contained in normalized_text'),
    ('# 查找参数名和值的组合', '# Find parameter name and value combinations'),
    ('# 查找目标文本', '# Find target text'),
    ('# 查找表头（No. h k l d）', '# Find table header (No. h k l d)'),
    ('# 查找角点', '# Find corners'),
    ('# 查找轮廓（角点）', '# Find contours (corners)'),
    ('# 查找黄色区域的轮廓', '# Find contours of yellow regions'),
    ('# 标准格式（归一化后）', '# Standard format (after normalization)'),
    ('# 标注填充信息', '# Annotate fill info'),
    ('# 标签可能是 Na0, NaO, Cl1, Cll 等变体', '# Labels may be variants like Na0, NaO, Cl1, Cll etc.'),
    ('# 标记中心', '# Mark center'),
    ('# 标记所有角点（灰色）', '# Mark all corners (gray)'),
    ('# 标记角点（绿色）', '# Mark corners (green)'),
    ('# 标记角点', '# Mark corners'),
    ('# 标题关键词的 OCR 误识别变体', '# OCR misrecognition variants of title keywords'),
    ('# 标题关键词变体', '# Title keyword variants'),
    ('# 标题都没找到，跳过这一帧', '# No title found, skip this frame'),
    ("# 核心证明：在对话框内是否出现了 'smart' 文本", "# Core proof: whether 'smart' text appears inside the dialog"),
    ('# 根据 match_mode 判断', '# Decision based on match_mode'),
    ('# 根据 x 坐标判断是第几个样式', '# Determine style index based on x coordinate'),
    ('# 根据区域裁剪', '# Crop by region'),
    ('# 格式1: [] - 空列表，只有 imported_files', '# Format 1: [] - empty list, only imported_files'),
    ('# 格式2: [["C1s Scan"]] - 单个状态', '# Format 2: [["C1s Scan"]] - single state'),
    ('# 格式3: [["C1s Scan"], ["C1s Scan", "O1s Scan"]] - 多个可能状态', '# Format 3: [["C1s Scan"], ["C1s Scan", "O1s Scan"]] - multiple possible states'),
    ('# 格式: "2     1    1    0    2.76169"', '# Format: "2     1    1    0    2.76169"'),
    ('# 格式: 元素符号 + 数字', '# Format: element symbol + number'),
    ('# 框边颜色验证（使用输入的shape_type）', '# Border color verification (using input shape_type)'),
    ('# 检查 other_files 的格式', '# Check format of other_files'),
    ('# 检查4个点是否接近理论角点（矩形的四个角）', '# Check if 4 points are close to theoretical corners (rectangle corners)'),
    ('# 检查R值格式1：R-数字 或 R=数字', '# Check R-value format 1: R-number or R=number'),
    ('# 检查profiles', '# Check profiles'),
    ('# 检查whether matched', '# Check whether matched'),
    ('# 检查whether matched任何一个文件', '# Check whether matched any file'),
    ('# 检查whether matched任意一个目标文本', '# Check whether matched any target text'),
    ('# 检查whether matched目标风格', '# Check whether matched target style'),
    ('# 检查whether matched预期值（允许5的倍数）', '# Check whether matched expected value (allow multiples of 5)'),
    ('# 检查whether matched，且该文件还没被当前帧记录过', '# Check whether matched, and file not yet recorded in current frame'),
    ('# 检查zoom关键词', '# Check zoom keywords'),
    ('# 检查参数名和值（原有逻辑）', '# Check parameter name and value (original logic)'),
    ('# 检查双向匹配 (A-B 或 B-A)', '# Check bidirectional match (A-B or B-A)'),
    ('# 检查各个设置项', '# Check each setting item'),
    ('# 检查导入的文件数量whether matched（包括重复的）', '# Check if imported file count matched (including duplicates)'),
    ('# 检查底部区域', '# Check bottom region'),
    ('# 检查弹窗标题是否存在', '# Check if dialog title exists'),
    ('# 检查必须关键词', '# Check required keywords'),
    ('# 检查所有禁止关键词（任意一个出现就算违规）', '# Check all forbidden keywords (any one appearing counts as violation)'),
    ('# 检查文本whether matched（尝试所有变体）', '# Check if text matched (try all variants)'),
    ('# 检查是否出现了小刻度', '# Check if small ticks appeared'),
    ('# 检查是否包含 @B: dm + 数字 的模式', '# Check if pattern @B: dm + number is present'),
    ('# 检查是否是 Boundary 对话框', '# Check if this is a Boundary dialog'),
    ('# 检查是否是坐标数值', '# Check if this is a coordinate value'),
    ('# 检查是否是目标原子行', '# Check if this is the target atom row'),
    ('# 检查是否有扩展名', '# Check if there is an extension'),
    ('# 检查是否有选中的行（通常以☑或checkbox标记）', '# Check if there is a selected row (usually marked with ☑ or checkbox)'),
    ('# 检查是否没有peaks', '# Check if there are no peaks'),
    ('# 检查标题是否存在', '# Check if title exists'),
    ('# 检查每个参数', '# Check each parameter'),
    ('# 检查点1: 文件打开 - 只要在all_files中有匹配就得分', '# Checkpoint 1: file open - score if any match found in all_files'),
    ('# 检查点2: 各种操作', '# Checkpoint 2: various operations'),
    ('# 检查点级别统计', '# Checkpoint-level statistics'),
    ('# 检查禁止关键词', '# Check forbidden keywords'),
    ('# 检查禁止词', '# Check forbidden words'),
    ('# 检查：正则表达式匹配 OR 用户传入的 normal_markers 匹配', '# Check: regex match OR user-provided normal_markers match'),
    ('# 检测 a, b, c', '# Detect a, b, c'),
    ('# 检测Axes菜单下拉内容', '# Detect Axes menu dropdown content'),
    ('# 检测位置变化', '# Detect position change'),
    ('# 检测区域', '# Detection region'),
    ('# 检测填充颜色', '# Detect fill color'),
    ('# 检测深色像素', '# Detect dark pixels'),
    ('# 检测目标颜色', '# Detect target color'),
    ('# 检测绿色', '# Detect green'),
    ('# 检测角点颜色', '# Detect corner color'),
    ('# 检测轮廓', '# Detect contours'),
    ('# 检测边缘', '# Detect edges'),
    ('# 检测顶部区域是否有.cif文件名', '# Detect if top region has a .cif filename'),
    ('# 检测黄色区域 (HSV)', '# Detect yellow region (HSV)'),
    ('# 椭圆上的点', '# Points on the ellipse'),
    ('# 椭圆形：采样椭圆边缘附近的像素', '# Ellipse: sample pixels near the ellipse edge'),
    ('# 步骤1: 检测标题 - 确认 Lattice Planes 弹窗存在', '# Step 1: Detect title - confirm Lattice Planes dialog exists'),
    ('# 步骤1: 检测标题 - 确认弹窗存在', '# Step 1: Detect title - confirm dialog exists'),
    ('# 步骤1: 检测标题', '# Step 1: Detect title'),
    ('# 步骤1: 生成理论得分（检查点级别）', '# Step 1: Generate theoretical scores (checkpoint level)'),
    ('# 步骤1: 生成理论得分', '# Step 1: Generate theoretical scores'),
    ('# 步骤2: 检测内容并清理 OCR 误识别', '# Step 2: Detect content and clean up OCR misrecognition'),
    ('# 步骤2: 检测内容', '# Step 2: Detect content'),
    ('# 步骤2: 检测顶部 50% 的表格内容', '# Step 2: Detect table content in top 50%'),
    ('# 步骤2: 运行批量评估（检查点级别）', '# Step 2: Run batch evaluation (checkpoint level)'),
    ('# 步骤2: 运行批量评估', '# Step 2: Run batch evaluation'),
    ('# 步骤3: 按行分割', '# Step 3: Split by line'),
    ('# 步骤3: 查找 No. 列下的行号', '# Step 3: Find row numbers under No. column'),
    ('# 步骤3: 根据字段匹配结果判定', '# Step 3: Decide based on field match results'),
    ('# 步骤3: 生成检查点级别对比报告', '# Step 3: Generate checkpoint-level comparison report'),
    ('# 步骤3: 统计 "3.39412" 出现次数', '# Step 3: Count "3.39412" occurrences'),
    ('# 步骤4: 查找目标原子的索引', '# Step 4: Find index of target atom'),
    ('# 步骤4: 状态判断', '# Step 4: State decision'),
    ('# 步骤4: 统计并判断', '# Step 4: Count and decide'),
    ('# 步骤5: 对每个找到的原子位置，向后查找坐标', '# Step 5: For each found atom position, search forward for coordinates'),
    ('# 步骤6: 验证坐标', '# Step 6: Verify coordinates'),
    ('# 每一行 OCR 文本最多只计入一个坐标轴标签，防止重复计数', '# Each OCR text line counted at most once as axis label, prevent duplicate counting'),
    ('# 每行只取第一个数字', '# Take only the first number from each line'),
    ('# 比较值（考虑浮点数误差）', '# Compare values (consider floating point error)'),
    ('# 比较坐标', '# Compare coordinates'),
    ('# 没有其他文件，只使用 imported_files', '# No other files, use imported_files only'),
    ('# 注意：不能全局替换 l → 1，因为 "Cl" 会变成 "C1"', '# Note: cannot globally replace l → 1, because "Cl" would become "C1"'),
    ('# 注意：我们通常在对话框左侧的背景列表区检测', '# Note: we usually detect in the background list area on the left side of the dialog'),
    ('# 添加大小写变体', '# Add case variants'),
    ('# 清理 OCR 误识别', '# Clean up OCR misrecognition'),
    ('# 清理常见误识别', '# Clean up common misrecognitions'),
    ('# 清空状态（仅输入框）', '# Clear state (input box only)'),
    ('# 灵活匹配（忽略大小写和空格）', '# Flexible matching (ignore case and spaces)'),
    ('# 生成变体', '# Generate variants'),
    ('# 生成可读检查点名称', '# Generate readable checkpoint names'),
    ('# 生成多种可能的 OCR 识别形式', '# Generate multiple possible OCR recognition forms'),
    ('# 生成总分矩阵对比 Excel', '# Generate total score matrix comparison Excel'),
    ('# 生成检查点名称', '# Generate checkpoint names'),
    ('# 生成裁剪后的截图路径', '# Generate path for cropped screenshot'),
    ('# 用于记录最佳匹配情况（即使失败也能看到离成功最近的一次）', '# For recording best match (even on failure, shows closest attempt to success)'),
    ('# 直接OCR完整截图', '# Directly OCR the full screenshot'),
    ('# 直接检查原始value_lower是否在operation中', '# Directly check if original value_lower is in operation'),
    ('# 直接连接', '# Direct concatenation'),
    ('# 矩形：保持原来的采样方式', '# Rectangle: keep original sampling method'),
    ('# 确保不超出图像边界', '# Ensure within image boundaries'),
    ('# 确保转为列表处理', '# Ensure converted to list for processing'),
    ('# 移除所有空格，方便匹配', '# Remove all spaces for easier matching'),
    ('# 第1优先级：短且独立的关键词（避免被长关键词的子串匹配）', '# Priority 1: short and independent keywords (avoid substring match by long keywords)'),
    ('# 第1步：裁剪左侧面板', '# Step 1: Crop left panel'),
    ('# 第2优先级：包含短关键词的长关键词', '# Priority 2: long keywords containing short keywords'),
    ('# 第2步：OCR识别', '# Step 2: OCR recognition'),
    ('# 第3.5步：检查是否能看到"Style"文字', '# Step 3.5: Check if "Style" text is visible'),
    ('# 第3优先级：其他关键词', '# Priority 3: other keywords'),
    ('# 第3步：检查弹窗', '# Step 3: Check dialog'),
    ('# 第4.5步：Fallback机制', '# Step 4.5: Fallback mechanism'),
    ('# 第4步：匹配Style关键词（最终修复版）', '# Step 4: Match Style keywords (final fix)'),
    ('# 第5步：如果没有检测到任何styles，直接返回None', '# Step 5: If no styles detected, return None directly'),
    ('# 第6步：蓝色检测', '# Step 6: Blue detection'),
    ('# 第7步：查找轮廓', '# Step 7: Find contours'),
    ('# 第8步：创建标记图', '# Step 8: Create annotation image'),
    ('# 第一步：优先检测文本', '# Step 1: Prioritize text detection'),
    ('# 第二步：视觉相似度比较', '# Step 2: Visual similarity comparison'),
    ('# 第二步：视觉相似度', '# Step 2: Visual similarity'),
    ('# 策略1: 匹配 mp-数字_元素.cif 格式', '# Strategy 1: match mp-number_element.cif format'),
    ('# 策略1: 精确匹配', '# Strategy 1: exact match'),
    ('# 策略1: 精确模式匹配', '# Strategy 1: exact pattern match'),
    ('# 策略2: 不区分大小写', '# Strategy 2: case-insensitive'),
    ('# 策略2: 匹配 .vesta 文件', '# Strategy 2: match .vesta files'),
    ('# 策略3: 匹配不带扩展名的文件', '# Strategy 3: match files without extension'),
    ('# 策略3: 去除空格后匹配', '# Strategy 3: match after removing spaces'),
    ('# 策略3: 规范化匹配', '# Strategy 3: normalized matching'),
    ('# 精确匹配或包含匹配', '# Exact match or contains match'),
    ('# 红色有两个HSV范围', '# Red has two HSV ranges'),
    ('# 绘制 Box 边界（黄色）', '# Draw Box boundary (yellow)'),
    ('# 绘制 ROI 框', '# Draw ROI box'),
    ('# 绘制分隔线（帮助判断是第几个）', '# Draw separator line (help determine index)'),
    ('# 绘制矩形边界（黄色）', '# Draw rectangle boundary (yellow)'),
    ('# 绘制调试图', '# Draw debug image'),
    ('# 统一加载图像', '# Load image uniformly'),
    ('# 统一转换为列表', '# Convert to list uniformly'),
    ('# 统一转换为列表格式', '# Convert to list format uniformly'),
    ('# 统计 Binding Energy', '# Count Binding Energy'),
    ('# 统计出现次数（不区分大小写）', '# Count occurrences (case-insensitive)'),
    ('# 统计匹配的期望文件', '# Count matched expected files'),
    ('# 统计变体出现次数（按行统计，避免子串问题）', '# Count variant occurrences (by line, avoid substring issues)'),
    ('# 统计当前帧匹配到了多少个期望文件', '# Count how many expected files matched in current frame'),
    ('# 统计摘要', '# Statistics summary'),
    ('# 统计识别到的唯一文件', '# Count identified unique files'),
    ('# 继续搜索但不要太远', '# Continue searching but not too far'),
    ('# 继续检查下一帧，可能后续帧有正确的值', '# Continue checking next frame; later frames may have correct values'),
    ('# 至少包含 "binding" 和 "energ" 的核心部分', '# Must contain core parts "binding" and "energ"'),
    ('# 至少需要 4 个数字: No, h, k, l', '# At least 4 numbers needed: No, h, k, l'),
    ('# 获取初始峰数量（第一个检测到的值，可以是0）', '# Get initial peak count (first detected value, can be 0)'),
    ('# 获取文本边界框', '# Get text bounding box'),
    ('# 获取最终峰数量（最后一个值）', '# Get final peak count (last value)'),
    ('# 获取详细的 OCR 数据', '# Get detailed OCR data'),
    ('# 获取轨迹的所有文件（主要文件 + 次要文件）', '# Get all files for trajectory (primary + secondary)'),
    ('# 表格在 "Calculate the best plane" 按钮下方', '# Table is below the "Calculate the best plane" button'),
    ('# 表格格式:', '# Table format:'),
    ('# 表格格式: No. | h | k | l | d | ...', '# Table format: No. | h | k | l | d | ...'),
    ('# 裁剪 "Ranges of fractional coordinates" 区域', '# Crop "Ranges of fractional coordinates" region'),
    ('# 裁剪 Boundary 对话框区域（左上角）', '# Crop Boundary dialog region (top-left)'),
    ('# 裁剪 Lattice Planes 对话框区域（左上角）', '# Crop Lattice Planes dialog region (top-left)'),
    ('# 裁剪 Orientation 对话框区域（左上角）', '# Crop Orientation dialog region (top-left)'),
    ('# 裁剪 Properties 弹窗所在的左侧区域', '# Crop the left region containing Properties dialog'),
    ('# 裁剪图像', '# Crop image'),
    ('# 裁剪表格区域', '# Crop table region'),
    ('# 解析 key，例如 "y_max" -> coordinate=\'y\', type=\'max\'', "# Parse key, e.g. \"y_max\" -> coordinate='y', type='max'"),
    ('# 计算 Box 边界', '# Calculate Box boundary'),
    ('# 计算 ROI 中心和尺寸', '# Calculate ROI center and size'),
    ('# 计算 SSIM', '# Calculate SSIM'),
    ('# 计算SSIM', '# Calculate SSIM'),
    ('# 计算中位数', '# Calculate median'),
    ('# 计算中心位移', '# Calculate center displacement'),
    ('# 计算中心和半径', '# Calculate center and radius'),
    ('# 计算匹配分数', '# Calculate match score'),
    ('# 计算填充比例', '# Calculate fill ratio'),
    ('# 计算增量', '# Calculate increment'),
    ('# 计算平均颜色', '# Calculate average color'),
    ('# 计算归一化的均方误差', '# Calculate normalized mean squared error'),
    ('# 计算得分', '# Calculate score'),
    ('# 计算每一帧的相似度', '# Calculate similarity for each frame'),
    ('# 计算相似度', '# Calculate similarity'),
    ('# 计算该检查点的理论得分', '# Calculate theoretical score for this checkpoint'),
    ('# 计算颜色像素占比', '# Calculate color pixel ratio'),
    ('# 计算颜色占比', '# Calculate color ratio'),
    ('# 计算黄色区域的中心点', '# Calculate center point of yellow region'),
    ('# 记录OCR结果到debug文件', '# Record OCR results to debug file'),
    ('# 记录中间状态，但不直接返回成功', '# Record intermediate state, do not return success directly'),
    ('# 记录全 0', '# Record all zeros'),
    ('# 记录失败的检查点', '# Record failed checkpoints'),
    ('# 记录总分', '# Record total score'),
    ('# 记录是否曾经找到过文本（用于最后的总结）', '# Record whether text was ever found (for final summary)'),
    ('# 记录第一个有效 ROI', '# Record first valid ROI'),
    ('# 记录细节（即使不通过也记录，便于调试）', '# Record details (record even if not passed, for debugging)'),
    ('# 记录非坐标行（用于调试）', '# Record non-coordinate lines (for debugging)'),
    ('# 评分逻辑：只要检测到至少一次菜单展开即得分', '# Scoring: score if menu expansion detected at least once'),
    ('# 评分：增加了恰好1个峰', '# Scoring: exactly 1 peak added'),
    ("# 详细得分：{轨迹ID: {任务名: {...}}}", "# Detailed scores: {trajectory_id: {task_name: {...}}}"),
    ('# 读取图片', '# Read image'),
    ('# 读取字段区域（左 40%，上 5%-65%）', '# Read field region (left 40%, top 5%-65%)'),
    ('# 读取截图', '# Read screenshot'),
    ('# 读取顶部区域', '# Read top region'),
    ('# 调整大小', '# Resize'),
    ('# 调整大小使其一致', '# Resize for consistency'),
    ('# 调试：确认规范化列表已正确设置', '# Debug: confirm normalized list is set correctly'),
    ('# 跳过包含标题的行', '# Skip lines containing headers'),
    ('# 跳过空行', '# Skip empty lines'),
    ('# 跳过第一个数字（行号），取后面三个作为 h, k, l', '# Skip first number (row index), take next three as h, k, l'),
    ('# 跳过表头', '# Skip table header'),
    ('# 跳过表头和其他关键词', '# Skip table header and other keywords'),
    ('# 转换为 OpenCV 格式', '# Convert to OpenCV format'),
    ('# 转换为 PIL Image', '# Convert to PIL Image'),
    ('# 转换为可序列化的格式', '# Convert to serializable format'),
    ('# 转换为灰度图', '# Convert to grayscale'),
    ('# 转换为相似度 (0-1)', '# Convert to similarity (0-1)'),
    ('# 转换为统一格式', '# Convert to unified format'),
    ('# 转换到 HSV', '# Convert to HSV'),
    ('# 转换到BGR和HSV颜色空间', '# Convert to BGR and HSV color space'),
    ('# 转换到HSV颜色空间', '# Convert to HSV color space'),
    ('# 转换期望值为字符串（支持整数和浮点数）', '# Convert expected value to string (supports int and float)'),
    ('# 过滤太小的区域（可能是噪点）', '# Filter out too-small regions (may be noise)'),
    ('# 过滤掉可能的误识别（如 1, 100 等不合理的值）', '# Filter out possible misrecognitions (e.g. 1, 100 or other unreasonable values)'),
    ('# 运行评估', '# Run evaluation'),
    ('# 返回值是对应的标准文件名（原始格式）', '# Return value is the corresponding standard filename (original format)'),
    ('# 这是复合检查，满分2分', '# This is a compound check, full score 2 points'),
    ('# 这种情况下，如果对应的对话框在，就给分', '# In this case, if the corresponding dialog is present, give score'),
    ('# 这里的区域逻辑保持原样（底部30%通常对应坐标轴）', '# Keep region logic as-is (bottom 30% usually corresponds to axis)'),
    ('# 遍历完所有截图后的总结', '# Summary after traversing all screenshots'),
    ('# 遍历完所有步骤', '# After traversing all steps'),
    ('# 遍历所有任务', '# Iterate over all tasks'),
    ('# 遍历所有截图，寻找Axes下拉菜单', '# Iterate all screenshots, look for Axes dropdown menu'),
    ('# 遍历所有截图，提取峰数量', '# Iterate all screenshots, extract peak counts'),
    ('# 遍历所有轨迹', '# Iterate over all trajectories'),
    ('# 部分匹配（有文本但数量不对）', '# Partial match (text found but count wrong)'),
    ('# 采样这两点之间的像素（椭圆边框区域）', '# Sample pixels between these two points (ellipse border region)'),
    ('# 错误反馈', '# Error feedback'),
    ('# 降低阈值到20%', '# Lower threshold to 20%'),
    ('# 需要恰好 3 个数字', '# Need exactly 3 numbers'),
    ('# 颜色一致性判断（找最一致的4个角点）', '# Color consistency check (find most consistent 4 corners)'),
    ('# 颜色一致性判断', '# Color consistency check'),
    ('# 颜色一致性检查', '# Color consistency check'),
    ('# 颜色一致性', '# Color consistency'),
    ('# 颜色范围定义', '# Color range definitions'),
    ('# 额外分：字段检查', '# Extra score: field check'),
    ('# 额外检查：如果目标是 "20 nm"，也匹配包含数字+单位的模式', '# Extra check: if target is "20 nm", also match patterns with number+unit'),
    ('# 高亮最佳矩形的角点（绿色）', '# Highlight corners of best rectangle (green)'),
    ('#简单评估函数', '# Simple evaluation functions'),
    # ---- string literals in dict/assignment ----
    ("'error': f\"轨迹初始化失败: {str(e)}\"", "'error': f\"Trajectory initialization failed: {str(e)}\""),
    ("'error': f\"轨迹初始化失败: {str(e)}\",", "'error': f\"Trajectory initialization failed: {str(e)}\","),
    ("'任务匹配率(%)':        f\"{exact_match / total_tests * 100:.1f}\"",
     "'task_match_rate(%)':        f\"{exact_match / total_tests * 100:.1f}\""),
    ("'任务匹配率(%)': f\"{(perfect_matches / total_tests * 100):.1f}\"",
     "'task_match_rate(%)': f\"{(perfect_matches / total_tests * 100):.1f}\""),
    ("'检查点':  f\"CP{idx+1}\"", "'checkpoint':  f\"CP{idx+1}\""),
    ("'检查点': f\"CP{idx+1}\"", "'checkpoint': f\"CP{idx+1}\""),
    ("'检查点匹配率(%)':", "'checkpoint_match_rate(%)':"),
    # ---- inline code comments ----
    ("'date': r'\\d{1,2}[/-]\\d{1,2}[/-]\\d{2,4}',      # 如 \"1/23/2023\"",
     "'date': r'\\d{1,2}[/-]\\d{1,2}[/-]\\d{2,4}',      # e.g. \"1/23/2023\""),
    ("'exposure_time': r'\\d+\\.?\\d*\\s*[sm]s?(?!\\w)',  # 如 \"0.1596 s\", \"100 ms\"",
     "'exposure_time': r'\\d+\\.?\\d*\\s*[sm]s?(?!\\w)',  # e.g. \"0.1596 s\", \"100 ms\""),
    ("'magnification': r'[xX]\\d{3,7}',               # 如 \"X330000\", \"x100k\"",
     "'magnification': r'[xX]\\d{3,7}',               # e.g. \"X330000\", \"x100k\""),
    ("'pixels': r'\\d{3,5}\\s*x\\s*\\d{3,5}\\s*pixels?',  # 如 \"4096 x 4096 pixels\"",
     "'pixels': r'\\d{3,5}\\s*x\\s*\\d{3,5}\\s*pixels?',  # e.g. \"4096 x 4096 pixels\""),
    ("'time': r'\\d{1,2}:\\d{2}:\\d{2}\\s*[AP]M',        # 如 \"10:12:53 AM\"",
     "'time': r'\\d{1,2}:\\d{2}:\\d{2}\\s*[AP]M',        # e.g. \"10:12:53 AM\""),
    ("'voltage': r'\\d{2,3}\\s*kV',                    # 如 \"300 kV\", \"200kV\"",
     "'voltage': r'\\d{2,3}\\s*kV',                    # e.g. \"300 kV\", \"200kV\""),
    # ---- function parameter descriptions ----
    ('**kwargs: 设置项，例如 y_max=2, z_max=2', '**kwargs: settings, e.g. y_max=2, z_max=2'),
    ('alternative_values: 可选的替代值列表(用于OCR误识别容错)', 'alternative_values: optional alternative value list (for OCR misrecognition tolerance)'),
    ('base_dir    : 包含 in1~in20 子文件夹的根目录', 'base_dir    : root directory containing in1~in20 subfolders'),
    ('base_dir: 基础目录，包含in1-in20子文件夹', 'base_dir: base directory containing in1-in20 subfolders'),
    ('bottom_percent: 下边界百分比 (0-100)', 'bottom_percent: lower boundary percentage (0-100)'),
    ('box_color: 框的颜色（用于记录）', 'box_color: box color (for logging)'),
    ('case_sensitive: 是否区分大小写（默认不区分）', 'case_sensitive: whether case-sensitive (default: no)'),
    ('check: 检查点配置', 'check: checkpoint configuration'),
    ('content: 方括号内的内容（已规范化）', 'content: content inside brackets (already normalized)'),
    ('corner_color: 角点的颜色（默认green）', 'corner_color: corner color (default green)'),
    ('corner_color: 角点颜色（默认 green）', 'corner_color: corner color (default green)'),
    ('dialog_title: dialog title关键词（如 "Profile Of 2"）', 'dialog_title: dialog title keyword (e.g. "Profile Of 2")'),
    ('dialog_title: 对话框标题', 'dialog_title: dialog title'),
    ('expected_count: 期望出现的次数（如 4）', 'expected_count: expected occurrence count (e.g. 4)'),
    ('expected_count: 期望的晶面数量', 'expected_count: expected crystal plane count'),
    ('expected_file: 期望的文件名', 'expected_file: expected filename'),
    ('expected_hkl: 期望的 Miller 指数 [h, k, l]，例如 [1, 0, 0]', 'expected_hkl: expected Miller indices [h, k, l], e.g. [1, 0, 0]'),
    ('expected_value: 期望值(主要值)', 'expected_value: expected value (primary value)'),
    ('expected_values: 期望的向量值列表 [h, k, l]，例如 [2, 2, 2]', 'expected_values: expected vector value list [h, k, l], e.g. [2, 2, 2]'),
    ('field_name: 字段名', 'field_name: field name'),
    ('filename: 文件名（可选，用于额外验证）', 'filename: filename (optional, for extra verification)'),
    ('fill_color: 填充颜色（默认 white）', 'fill_color: fill color (default white)'),
    ('forbidden_keywords: 禁止出现的关键词列表（例如 ["Import Document"]），可为 None',
     'forbidden_keywords: list of forbidden keywords (e.g. ["Import Document"]), can be None'),
    ('forbidden_keywords=None,  # 禁止出现的关键词列表（可传 None 或空列表）',
     'forbidden_keywords=None,  # list of forbidden keywords (can be None or empty list)'),
    ('keyword: str,                           # 必须出现的关键词',
     'keyword: str,                           # keyword that must appear'),
    ('keyword: 必须出现的关键词（字符串）', 'keyword: keyword that must appear (string)'),
    ('left_percent: 左边界百分比 (0-100)', 'left_percent: left boundary percentage (0-100)'),
    ('min_keywords: 至少匹配的关键词数量（默认2个）', 'min_keywords: minimum number of keywords to match (default 2)'),
    ('output_dir  : 输出目录（可选）', 'output_dir  : output directory (optional)'),
    ('output_dir: 基础目录，包含in1-in20子文件夹', 'output_dir: base directory containing in1-in20 subfolders'),
    ('output_dir: 输出目录（可选）', 'output_dir: output directory (optional)'),
    ('output_dir: 输出目录', 'output_dir: output directory'),
    ('Returns: (相似度分数, 裁剪后的截图路径)', 'Returns: (similarity score, path to cropped screenshot)'),
    ('actual_file: 实际的文件名', 'actual_file: actual filename'),
    ('all_files = imported_files + other_files  # 合并所有文件',
     'all_files = imported_files + other_files  # merge all files'),
    # ---- check_name assignments ----
    ('check_name = "平滑+背景扣除"', 'check_name = "smooth+bg-subtraction"'),
    ("check_name = f\"关键词:{args.get('keyword', '')[:15]}\"", "check_name = f\"keyword:{args.get('keyword', '')[:15]}\""),
    ('check_name = f"参数设置"', 'check_name = f"param-settings"'),
    ("check_name = f\"字段:{field}={value}\"[:20]", "check_name = f\"field:{field}={value}\"[:20]"),
    ("check_name = f\"对话框:{args.get('dialog_title', '')[:15]}\"", "check_name = f\"dialog:{args.get('dialog_title', '')[:15]}\""),
    ("check_name = f\"对话框:{args.get('expected_title', '')[:15]}\"", "check_name = f\"dialog:{args.get('expected_title', '')[:15]}\""),
    ("check_name = f\"对话框:{args.get('title_keyword', '')[:15]}\"", "check_name = f\"dialog:{args.get('title_keyword', '')[:15]}\""),
    ("check_name = f\"导入:{','.join(files[:2])}\" if len(files) <= 2 else f\"导入:{len(files)}个文件\"",
     "check_name = f\"import:{','.join(files[:2])}\" if len(files) <= 2 else f\"import:{len(files)}_files\""),
    ("check_name = f\"弹窗:{args['title'][:20]}\"", "check_name = f\"dialog:{args['title'][:20]}\""),
    ("check_name = f\"打开:{file[:15]}\"", "check_name = f\"open:{file[:15]}\""),
    ("check_name = f\"打开文件:{args['expected_filename']}\"", "check_name = f\"open_file:{args['expected_filename']}\""),
    ("check_name = f\"视觉:{args.get('reference_key', '')[:10]}\"", "check_name = f\"visual:{args.get('reference_key', '')[:10]}\""),
    ('check_value = True  # 是否检查值', 'check_value = True  # whether to check value'),
    # ---- error_log messages ----
    ('error_log.append(f"{folder_id} ({display_name}): 初始化失败 - {str(e)}")',
     'error_log.append(f"{folder_id} ({display_name}): initialization failed - {str(e)}")'),
    ('error_log.append(f"{folder_id} ({display_name}): 文件夹不存在")',
     'error_log.append(f"{folder_id} ({display_name}): folder does not exist")'),
    ('error_log.append(f"{traj_id}: 初始化失败 - {e}")',
     'error_log.append(f"{traj_id}: initialization failed - {e}")'),
    ('error_log.append(f"{traj_id}: 初始化失败 - {str(e)}")',
     'error_log.append(f"{traj_id}: initialization failed - {str(e)}")'),
    ('error_log.append(f"{traj_id}: 文件夹不存在")',
     'error_log.append(f"{traj_id}: folder does not exist")'),
    # ---- f-string log messages ----
    ('f"  4个{corner_color}色角点"', 'f"  4 {corner_color} corners"'),
    ('f"  Y方向位移: {dy:.0f} > {threshold_y:.0f}（阈值）"', 'f"  Y displacement: {dy:.0f} > {threshold_y:.0f} (threshold)"'),
    ("f\"  [步骤 {i:02d}] Bonds 表格有键，'3.39412' 出现 {count} 次\"",
     "f\"  [Step {i:02d}] Bonds table has bonds, '3.39412' appears {count} times\""),
    ('f"  [步骤 {i:02d}] 坐标不匹配: 期望 {expected_coords}, 实际 {detected_coords}"',
     'f"  [Step {i:02d}] Coordinates mismatch: expected {expected_coords}, actual {detected_coords}"'),
    ('f"  [步骤 {i:02d}] 数量不匹配: 期望 {expected_count}, 实际 {len(row_numbers)}"',
     'f"  [Step {i:02d}] Count mismatch: expected {expected_count}, actual {len(row_numbers)}"'),
    ('f"  [步骤 {i}] OpenCV 检测: 第 {detected_style} 个样式 (中心点 x={cx}, area={area:.0f})"',
     'f"  [Step {i}] OpenCV detection: style #{detected_style} (center x={cx}, area={area:.0f})"'),
    ('f"  [步骤 {i}] Upward vector 不匹配: 期望 {expected_values}, 实际 {detected_values}"',
     'f"  [Step {i}] Upward vector mismatch: expected {expected_values}, actual {detected_values}"'),
    ('f"  [步骤 {i}] 提取到 Upward vector: h={detected_values[0]}, k={detected_values[1]}, l={detected_values[2]}"',
     'f"  [Step {i}] Extracted Upward vector: h={detected_values[0]}, k={detected_values[1]}, l={detected_values[2]}"'),
    ('f"  [步骤 {i}] 检测到 {len(result[\'details\'][\'detected_planes\'])} 个平面，但没有 {expected_hkl}"',
     'f"  [Step {i}] Detected {len(result[\'details\'][\'detected_planes\'])} planes, but none matching {expected_hkl}"'),
    ('f"  ✓ 检测到有效 ROI: 中心=({center_x:.0f}, {center_y:.0f}), "',
     'f"  ✓ Valid ROI detected: center=({center_x:.0f}, {center_y:.0f}), "'),
    ('f"  位移: dx={dx:.0f}, dy={dy:.0f}, 阈值(30%高度)={threshold_y:.0f}"',
     'f"  Displacement: dx={dx:.0f}, dy={dy:.0f}, threshold(30% height)={threshold_y:.0f}"'),
    ("f\"  位置: ({box['x_min']}, {box['y_min']})\\n\"", "f\"  Position: ({box['x_min']}, {box['y_min']})\\n\""),
    ("f\"  内部填充比例: {box['fill_ratio']*100:.1f}%\\n\"", "f\"  Interior fill ratio: {box['fill_ratio']*100:.1f}%\\n\""),
    ("f\"  原位置: ({first_roi_info['center_x']:.0f}, {first_roi_info['center_y']:.0f})\\n\"",
     "f\"  Original position: ({first_roi_info['center_x']:.0f}, {first_roi_info['center_y']:.0f})\\n\""),
    ('f"  原图尺寸: {height}x{width}, "', 'f"  Original size: {height}x{width}, "'),
    ('f"  可能未执行放大覆盖操作"', 'f"  Zoom-cover operation may not have been performed"'),
    ('f"  在弹窗中检测到 \'{target_text}\' 出现 {count} 次 (期望 {expected_count} 次)"',
     'f"  Detected \'{target_text}\' {count} times in dialog (expected {expected_count} times)"'),
    ("f\"  尺寸: {box['width']}x{box['height']} 像素\\n\"", "f\"  Size: {box['width']}x{box['height']} pixels\\n\""),
    ("f\"  新位置: ({valid_roi['center_x']:.0f}, {valid_roi['center_y']:.0f})\\n\"",
     "f\"  New position: ({valid_roi['center_x']:.0f}, {valid_roi['center_y']:.0f})\\n\""),
    ('f"  组合 {combo}: Box=({x_min},{y_min},{box_width},{box_height}), "',
     'f"  Combination {combo}: Box=({x_min},{y_min},{box_width},{box_height}), "'),
    ('f"(检查点: {len(task_checks)})")', 'f"(checkpoints: {len(task_checks)})")'),
    ('f"(顶{crop_top}~底{crop_bottom}, 左0~右{crop_right})"',
     'f"(top{crop_top}~bottom{crop_bottom}, left0~right{crop_right})"'),
    ('f"HSV中位数:({median_h:.0f},{median_s:.0f},{median_v:.0f})", "INFO")',
     'f"HSV median:({median_h:.0f},{median_s:.0f},{median_v:.0f})", "INFO")'),
    ('f"method_{keyword}",  # 对于方法类关键词', 'f"method_{keyword}",  # for method-type keywords'),
    ('f"{len([t for t in trajectories if t in actual_details])} 条轨迹")',
     'f"{len([t for t in trajectories if t in actual_details])} trajectories")'),
    ('f"⚠ [步骤 {i}] \'{target_text}\' 出现次数不匹配: {count} != {expected_count}"',
     'f"⚠ [Step {i}] \'{target_text}\' count mismatch: {count} != {expected_count}"'),
    ('f"⚠ 弹窗已打开，但字段匹配不完整: {matched_count}/{total_count}"',
     'f"⚠ Dialog opened but field match incomplete: {matched_count}/{total_count}"'),
    ('f"⚠ 检测到 ROI 但位置未发生显著变化\\n"',
     'f"⚠ ROI detected but position did not change significantly\\n"'),
    ('f"⚠ 部分完成: 最终相似度 {final_sim:.4f} 有提升但未达到阈值 {similarity_threshold:.4f}"',
     'f"⚠ Partially complete: final similarity {final_sim:.4f} improved but below threshold {similarity_threshold:.4f}"'),
    ('f"⚠ 部分完成: 最终相似度 {final_sim:.4f} 有提升但未达到阈值 {similarity_threshold}"',
     'f"⚠ Partially complete: final similarity {final_sim:.4f} improved but below threshold {similarity_threshold}"'),
    ('f"✓ [步骤 {i:02d}] Bonds 表格已清空"', 'f"✓ [Step {i:02d}] Bonds table cleared"'),
    ('f"✓ [步骤 {i}] \'{target_text}\' 出现次数匹配: {count} == {expected_count}"',
     'f"✓ [Step {i}] \'{target_text}\' count matched: {count} == {expected_count}"'),
    ('f"✓ [步骤 {i}] 检测到 Data Bar 文本特征: "', 'f"✓ [Step {i}] Data Bar text features detected: "'),
    ('f"✓ [步骤 {i}] 检测到填充的{fill_color}色 Box:\\n"', 'f"✓ [Step {i}] Detected {fill_color}-filled Box:\\n"'),
    ('f"✓ 发现Args: {param_name}={expect_val} (截图{i}, {region})"',
     'f"✓ Found args: {param_name}={expect_val} (screenshot {i}, {region})"'),
    ('f"✓ 发现参数名: {param_name} (截图{i}, {region})"',
     'f"✓ Found param name: {param_name} (screenshot {i}, {region})"'),
    ('f"✓ 发现弹窗: {dialog_title} (截图{i}, {region})"',
     'f"✓ Found dialog: {dialog_title} (screenshot {i}, {region})"'),
    ('f"✓ 坐标轴成功切换: {result[\'details\'][\'initial_state\']} → {result[\'details\'][\'final_state\']} "',
     'f"✓ Axis switched successfully: {result[\'details\'][\'initial_state\']} → {result[\'details\'][\'final_state\']} "'),
    ('f"✓ 成功完成平移: 最大相似度 {max_sim:.4f} (步骤 {result[\'details\'][\'max_similarity_step\']:02d})"',
     'f"✓ Translation completed: max similarity {max_sim:.4f} (step {result[\'details\'][\'max_similarity_step\']:02d})"'),
    ('f"✓ 成功旋转90度: 最大相似度 {max_sim:.4f} (步骤 {result[\'details\'][\'max_similarity_step\']:02d})"',
     'f"✓ 90-degree rotation completed: max similarity {max_sim:.4f} (step {result[\'details\'][\'max_similarity_step\']:02d})"'),
    ('f"✓ 成功旋转到标准取向: 最大相似度 {max_sim:.4f} (步骤 {result[\'details\'][\'max_similarity_step\']:02d})"',
     'f"✓ Standard orientation achieved: max similarity {max_sim:.4f} (step {result[\'details\'][\'max_similarity_step\']:02d})"'),
    ('f"✓ 检测到{atom_type}原子信息弹窗 (步骤 {i}, {region_name})"',
     'f"✓ {atom_type} atom info dialog detected (step {i}, {region_name})"'),
    ('f"✓ 步骤 {i}: ROI 位置显著变化！\\n"', 'f"✓ Step {i}: ROI position changed significantly!\\n"'),
    ('f"✓ 步骤 {i}: 检测到第一个 ROI，中心=({center_x:.0f}, {center_y:.0f})"',
     'f"✓ Step {i}: First ROI detected, center=({center_x:.0f}, {center_y:.0f})"'),
    ("f\"✗ Bonds 表格未被清空（'3.39412' 始终出现 {initial_count} 次）\"",
     "f\"✗ Bonds table not cleared ('3.39412' always appears {initial_count} times)\""),
    ("f\"✗ Upward vector 错误: 期望 {expected_values}, 实际 {result['details']['detected_values']}\"",
     "f\"✗ Upward vector error: expected {expected_values}, actual {result['details']['detected_values']}\""),
    ('f"✗ [步骤 {i}] 未在弹窗中检测到 \'{target_text}\'"',
     'f"✗ [Step {i}] \'{target_text}\' not detected in dialog"'),
    ('f"✗ {atom_label} 坐标错误: 期望 {expected_coords}, 实际 {result[\'details\'][\'detected_coords\']}"',
     'f"✗ {atom_label} coordinate error: expected {expected_coords}, actual {result[\'details\'][\'detected_coords\']}"'),
    ('f"✗ 元素 \'{element_name}\' 最多出现 {result[\'details\'][\'max_count\']} 次，"',
     'f"✗ Element \'{element_name}\' appeared at most {result[\'details\'][\'max_count\']} times, "'),
    ('f"✗ 晶面数量不匹配: 期望 {expected_count}, 实际 {result[\'details\'][\'detected_count\']}"',
     'f"✗ Crystal plane count mismatch: expected {expected_count}, actual {result[\'details\'][\'detected_count\']}"'),
    ('f"✗ 未完成平移: 最大相似度 {max_sim:.4f} < 阈值 {similarity_threshold:.4f}"',
     'f"✗ Translation not completed: max similarity {max_sim:.4f} < threshold {similarity_threshold:.4f}"'),
    ('f"✗ 未找到 hkl={expected_hkl} 的平面。检测到的平面: {result[\'details\'][\'detected_planes\']}"',
     'f"✗ Plane with hkl={expected_hkl} not found. Detected planes: {result[\'details\'][\'detected_planes\']}"'),
    ('f"✗ 未达到旋转90度: 最大相似度 {max_sim:.4f} < 阈值 {similarity_threshold}"',
     'f"✗ 90-degree rotation not achieved: max similarity {max_sim:.4f} < threshold {similarity_threshold}"'),
    ('f"✗ 未达到标准取向: 最大相似度 {max_sim:.4f} < 阈值 {similarity_threshold}"',
     'f"✗ Standard orientation not achieved: max similarity {max_sim:.4f} < threshold {similarity_threshold}"'),
    ('f"✗ 检测到弹窗但 \'{target_text}\' 出现次数不符: "', 'f"✗ Dialog detected but \'{target_text}\' count incorrect: "'),
    ('f"✗ 检测到第 {result[\'details\'][\'selected_style\']} 个样式，但期望第 {style_number} 个"',
     'f"✗ Detected style #{result[\'details\'][\'selected_style\']}, but expected style #{style_number}"'),
    ('f"✗ 状态未改变: {result[\'details\'][\'initial_state\']} "', 'f"✗ State unchanged: {result[\'details\'][\'initial_state\']} "'),
    ('f"内部{fill_color}色填充={fill_ratio*100:.1f}%"', 'f"Interior {fill_color} fill={fill_ratio*100:.1f}%"'),
    ('f"匹配 {len(matched)} 个关键词 ({keyword_summary})"', 'f"Matched {len(matched)} keywords ({keyword_summary})"'),
    ('f"匹配度:{border_info[\'max_match_ratio\']*100:.1f}%, "', 'f"Match ratio:{border_info[\'max_match_ratio\']*100:.1f}%, "'),
    ('f"匹配角={matched_corners}/4, 总得分={score:.1f}", "INFO")', 'f"Matched corners={matched_corners}/4, total score={score:.1f}", "INFO")'),
    ('f"尺寸={width:.0f}x{height:.0f}"', 'f"Size={width:.0f}x{height:.0f}"'),
    ('f"搜索区域: {search_height}x{search_width} "', 'f"Search region: {search_height}x{search_width} "'),
    ('f"期望 {expected_count} 次"', 'f"expected {expected_count} times"'),
    ('f"检查点: {cp_scores}")', 'f"checkpoints: {cp_scores}")'),
    ('f"深色{dark_ratio:.2%}, 边缘{edge_ratio:.2%}, 轮廓{len(significant_contours)}, 分数{score:.1f}", "DEBUG")',
     'f"dark{dark_ratio:.2%}, edge{edge_ratio:.2%}, contours{len(significant_contours)}, score{score:.1f}", "DEBUG")'),
    ("f.write(f\"批量评估错误日志  {datetime.now():%Y-%m-%d %H:%M:%S}\\n{'='*70}\\n\")",
     "f.write(f\"Batch evaluation error log  {datetime.now():%Y-%m-%d %H:%M:%S}\\n{'='*70}\\n\")"),
    ('f.write(f"批量评估错误日志\\n")', 'f.write(f"Batch evaluation error log\\n")'),
    ("f.write(f\"时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n\")",
     "f.write(f\"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n\")"),
    ('field_msg = f" + 字段检查{field_checks}" if field_checks else ""',
     'field_msg = f" + field_checks:{field_checks}" if field_checks else ""'),
    ('for base_val in value_patterns[:1]:  # 只用基础值', 'for base_val in value_patterns[:1]:  # use base value only'),
    ('for task_name in sorted(theo_details[list(theo_details.keys())[0]].keys()):  # 从第一个轨迹获取任务列表',
     'for task_name in sorted(theo_details[list(theo_details.keys())[0]].keys()):  # get task list from first trajectory'),
    ('forbidden_keywords = forbidden_keywords or []  # 如果 None，转为空列表',
     'forbidden_keywords = forbidden_keywords or []  # if None, convert to empty list'),
    ('if area < 100:  # 最小面积阈值', 'if area < 100:  # minimum area threshold'),
    ('if ratio > 0.15:  # 15%的像素匹配即可', 'if ratio > 0.15:  # 15% pixel match is sufficient'),
    # print statements
    ('print("\\n✅ 全部完成！")', 'print("\\n✅ All done!")'),
    ('print("\\n✅ 所有步骤完成！")', 'print("\\n✅ All steps complete!")'),
    ('print("\\n步骤2: 运行批量评估（400个实验，记录检查点）...")',
     'print("\\nStep 2: Running batch evaluation (400 experiments, recording checkpoints)...")'),
    ('print("\\n步骤3: 生成检查点级别对比报告...")',
     'print("\\nStep 3: Generating checkpoint-level comparison report...")'),
    ('print("\\n生成检查点级别对比表...")', 'print("\\nGenerating checkpoint-level comparison table...")'),
    ('print("仅生成理论得分，程序结束。")', 'print("Only generating theoretical scores, program ends.")'),
    ('print("步骤 1: 生成理论得分矩阵（检查点级别）...")',
     'print("Step 1: Generating theoretical score matrix (checkpoint level)...")'),
    ('print("步骤 2: 运行批量评估（400 个实验）...")',
     'print("Step 2: Running batch evaluation (400 experiments)...")'),
    ('print("步骤 3: 生成检查点级别对比报告...")',
     'print("Step 3: Generating checkpoint-level comparison report...")'),
    ('print("步骤1: 生成理论得分矩阵（检查点级别）...")',
     'print("Step 1: Generating theoretical score matrix (checkpoint level)...")'),
    ('print("评估统计")', 'print("Evaluation statistics")'),
    ('print()  # 空行分隔', 'print()  # blank line separator'),
    ("print(f\"       ❌ 错误: {e}\")", "print(f\"       ❌ Error: {e}\")"),
    ("print(f\"       得分: {total}/{result['max_score']}  \"", "print(f\"       Score: {total}/{result['max_score']}  \""),
    ("print(f\"      ✓ 得分: {total_score}/{result['max_score']}\"", "print(f\"      ✓ Score: {total_score}/{result['max_score']}\""),
    ("print(f\"      ✓ 检查点得分: {checkpoint_scores}\"", "print(f\"      ✓ Checkpoint scores: {checkpoint_scores}\""),
    ("print(f\"      ❌ 错误: {str(e)}\")", "print(f\"      ❌ Error: {str(e)}\")"),
    ("print(f\"      检查点数量: {len(task_checks)}\"", "print(f\"      Checkpoint count: {len(task_checks)}\""),
    ("print(f\"    ❌ 错误: {str(e)}\")", "print(f\"    ❌ Error: {str(e)}\")"),
    ("print(f\"    得分: {total_score}/{result['max_score']}\"", "print(f\"    Score: {total_score}/{result['max_score']}\""),
    ("print(f\"    检查点: {checkpoint_scores}\"", "print(f\"    Checkpoints: {checkpoint_scores}\""),
    ('print(f"  ✓ 实际总分矩阵: {actual_xlsx}")', 'print(f"  ✓ Actual total score matrix: {actual_xlsx}")'),
    ('print(f"  ✓ 实际详细得分: {actual_json}\\n")', 'print(f"  ✓ Actual detailed scores: {actual_json}\\n")'),
    ('print(f"  ✓ 截图数量: {len(evaluator.screenshots)}")', 'print(f"  ✓ Screenshot count: {len(evaluator.screenshots)}")'),
    ('print(f"  ✓ 理论总分矩阵: {theo_xlsx}")', 'print(f"  ✓ Theoretical total score matrix: {theo_xlsx}")'),
    ('print(f"  ✓ 理论详细得分: {theo_json}\\n")', 'print(f"  ✓ Theoretical detailed scores: {theo_json}\\n")'),
    ('print(f"  ✓ 评估器初始化完成")', 'print(f"  ✓ Evaluator initialized")'),
    ('print(f"  步骤 [{i:02d}] | Style: {style_text:15s} | 左侧面板: {left_panel_path:40s} | 标记图: {marked_path}")',
     'print(f"  Step [{i:02d}] | Style: {style_text:15s} | Left panel: {left_panel_path:40s} | Marked: {marked_path}")'),
    ('print(f"  步骤 [{i:02d}] | 相似度: {similarity:.4f} | 裁剪图: {cropped_path.name if cropped_path else \'N/A\'}")',
     'print(f"  Step [{i:02d}] | Similarity: {similarity:.4f} | Crop: {cropped_path.name if cropped_path else \'N/A\'}")'),
    ('print(f"  步骤 [{i:02d}] | 相似度: {similarity:.4f} | 路径: {cropped_path.name if cropped_path else \'N/A\'}")',
     'print(f"  Step [{i:02d}] | Similarity: {similarity:.4f} | Path: {cropped_path.name if cropped_path else \'N/A\'}")'),
    ('print(f"DigitalMicrograph 评估系统 v1.0")', 'print(f"DigitalMicrograph Evaluation System v1.0")'),
    # ---- misc remaining docstring fragments ----
    ('Data Bar 典型特征：', 'Data Bar typical features:'),
    ('DigitalMicrograph在顶部显示格式:', 'DigitalMicrograph top display format:'),
    ('0 或 1 (该检查点是否应该得分)', '0 or 1 (whether this checkpoint should score)'),
    ('1. OCR 检测：必须同时检测到 "zoom in" 文本 和 "Step(%) = 100"',
     '1. OCR detection: must simultaneously detect "zoom in" text and "Step(%) = 100"'),
    ('1. 先检测 4 个绿色角点（定位 Box 框）', '1. First detect 4 green corners (locate Box frame)'),
    ('1. 先通过OCR定位文本位置', '1. First locate text position via OCR'),
    ('1. 标题数量完全匹配（支持同名文件）', '1. Title count fully matched (supports same-name files)'),
    ('1. 检测到第一个有效 ROI（4个颜色一致的绿色角点）', '1. First valid ROI detected (4 consistent green corners)'),
    ('1. 检测顶部 5% 确认 Lattice Planes 弹窗存在', '1. Detect top 5% to confirm Lattice Planes dialog exists'),
    ('1. 识别出的文件列表中包含所有期望的文件', '1. Identified file list contains all expected files'),
    ('2. "Binding Energy" 坐标轴标签数量必须严格等于期望的文件总数',
     '2. "Binding Energy" axis label count must strictly equal expected total file count'),
    ('2. 再检查框内部是否填充了目标颜色', '2. Then check if box interior is filled with target color'),
    ('2. 检测到 ROI 位置发生显著变化（Y坐标中心移动 > 原高度的30%）',
     '2. ROI position significantly changed (Y center moved > 30% of original height)'),
    ('2. 检测顶部 50% 的表格内容', '2. Detect table content in top 50%'),
    ('2. 正确处理弹窗遮挡（has_style_text检查）', '2. Correctly handle dialog occlusion (has_style_text check)'),
    ('2. 然后检测该位置的颜色whether matched', '2. Then detect color at that position to check if matched'),
    ('2. 视觉比对：如果文本检测失败，则与 100% 缩放后的参考图对比',
     '2. Visual comparison: if text detection fails, compare with 100% scaled reference image'),
    ('2. 该截图中的 "Binding Energy" 标签数量等于期望文件数量',
     '2. "Binding Energy" label count in screenshot equals expected file count'),
    ('3. 统计 No. 列下的行号数量', '3. Count row numbers under No. column'),
    # ---- bullet list items ----
    ('- "@B: dm1" 或 "@C: dm2" (在窗口最顶部)', '- "@B: dm1" or "@C: dm2" (at the very top of the window)'),
    ('- checkpoint_comparison_<时间戳>.xlsx  （各任务检查点明细）',
     '- checkpoint_comparison_<timestamp>.xlsx  (checkpoint details per task)'),
    ('- summary_matrices_<时间戳>.xlsx       （总分/差异/准确率矩阵）',
     '- summary_matrices_<timestamp>.xlsx       (total score/diff/accuracy matrices)'),
    ('- 仅在菜单栏看到"Axes"文本 ≠ 选择了Axes（可能只是显示）',
     '- Seeing "Axes" in menu bar ≠ Axes selected (may be display only)'),
    ('- 例如：2 Peaks → 3 Peaks', '- e.g.: 2 Peaks → 3 Peaks'),
    ('- 像素信息（如 4096 x 4096 pixels）', '- Pixel info (e.g. 4096 x 4096 pixels)'),
    ('- 字段检测：完整区域（不再限制在左40%）', '- Field detection: full region (no longer limited to left 40%)'),
    ('- 字段检测：左 40%，上 60% 区域（弹窗主体内容区域）', '- Field detection: left 40%, top 60% region (main dialog content area)'),
    ('- 底部20%区域的峰数量从 X Peaks 变成 X+1 Peaks', '- Peak count in bottom 20% changes from X Peaks to X+1 Peaks'),
    ('- 必须检测到Axes特有的菜单项（如X-axis选项、Y轴选项）', '- Must detect Axes-specific menu items (e.g. X-axis options, Y-axis options)'),
    ('- 必须检测到下拉菜单展开才算完成指令', '- Must detect dropdown menu expansion to count as instruction complete'),
    ('- 放大倍数（如 X330000）', '- Magnification (e.g. X330000)'),
    ('- 日期时间', '- Date/time'),
    ('- 曝光时间（如 0.1596 s）', '- Exposure time (e.g. 0.1596 s)'),
    ('- 标题检测：顶部 5% 区域', '- Title detection: top 5% region'),
    ('- 电压信息（如 300 kV）', '- Voltage info (e.g. 300 kV)'),
    ('- 设备名称（如 OneView）', '- Device name (e.g. OneView)'),
    ('- 阈值：≥3个菜单项表示菜单已展开', '- Threshold: ≥3 menu items indicates menu is expanded'),
    # msg variable
    ('msg = f"✓ 文件 {expected_filename} 初始打开 (识别为: {self.current_file})"',
     'msg = f"✓ File {expected_filename} initially opened (recognized as: {self.current_file})"'),
    ('msg = f"✓ 文件 {expected_filename} 在步骤 {found_index} 打开 (识别为: {self.current_file})"',
     'msg = f"✓ File {expected_filename} opened at step {found_index} (recognized as: {self.current_file})"'),
    # log_msg variable
    ('log_msg = f"检查关键词: {keyword}"', 'log_msg = f"Checking keyword: {keyword}"'),
    ('log_msg = f"检查对话框标题: {expected_title}"', 'log_msg = f"Checking dialog title: {expected_title}"'),
    ('log_msg += f" (区域: {region})"', 'log_msg += f" (region: {region})"'),
    ('log_msg += f" (禁止: {\', \'.join(forbidden_keywords)})"', 'log_msg += f" (forbidden: {\', \'.join(forbidden_keywords)})"'),
    # label assignments
    ("label = f\"OCR新出现:{a.get('target_text','')}\"", "label = f\"OCR_new:{a.get('target_text','')}\""),
    ("label = f\"导入:{a.get('expected_filename','')}\"", "label = f\"import:{a.get('expected_filename','')}\""),
    ("label = f\"工具:{a.get('tool_name','')}\"", "label = f\"tool:{a.get('tool_name','')}\""),
    ("label = f\"弹窗:{a.get('title_keyword','')}\"", "label = f\"dialog:{a.get('title_keyword','')}\""),
    ("label = f\"文字色:{a.get('color_name','')}\"", "label = f\"text_color:{a.get('color_name','')}\""),
    ("label = f\"文字色变化:{a.get('text','')}→{a.get('color_name','')}\"",
     "label = f\"text_color_change:{a.get('text','')}→{a.get('color_name','')}\""),
    ("label = f\"框色:{a.get('box_color','')}-{a.get('shape_type','box')}\"",
     "label = f\"border_color:{a.get('box_color','')}-{a.get('shape_type','box')}\""),
    # num_samples comment
    ('num_samples = 36  # 采样36个点（每10度一个）', 'num_samples = 36  # sample 36 points (one every 10 degrees)'),
    # continue comments
    ('continue  # 如果发现peaks，跳过这个截图', 'continue  # if peaks found, skip this screenshot'),
    ('continue  # 继续找下一帧，而不是直接返回', 'continue  # continue to next frame, do not return directly'),
    # misc
    ("coordinate = match.group(1)  # x, y, 或 z", "coordinate = match.group(1)  # x, y, or z"),
    ("min_or_max = match.group(2)  # min 或 max", "min_or_max = match.group(2)  # min or max"),
    ('detected_style = max(1, min(6, detected_style))  # 限制在 1-6 范围', 'detected_style = max(1, min(6, detected_style))  # clamp to range 1-6'),
    ('max_mse = 255 ** 2  # 最大可能的MSE', 'max_mse = 255 ** 2  # maximum possible MSE'),
    # crop variables
    ('crop_bottom = int(height * 0.85)   # 去掉底部15%（保留到85%）', 'crop_bottom = int(height * 0.85)   # remove bottom 15% (keep up to 85%)'),
    ('crop_right = int(width * 0.5)      # 只保留左侧50%', 'crop_right = int(width * 0.5)      # keep left 50% only'),
    ('crop_top = int(height * 0.15)      # 去掉顶部15%', 'crop_top = int(height * 0.15)      # remove top 15%'),
    # OpenCV annotations
    ('cv2.circle(debug_img, (cx, cy), 8, (255, 0, 0), -1)  # 蓝色圆点', 'cv2.circle(debug_img, (cx, cy), 8, (255, 0, 0), -1)  # blue dot'),
    ('cv2.drawContours(debug_img, [largest_contour], -1, (0, 255, 0), 2)  # 绿色轮廓', 'cv2.drawContours(debug_img, [largest_contour], -1, (0, 255, 0), 2)  # green contour'),
    # int calculations with comments
    ('int(dialog_height * 0.12),  # top (Material 下方)', 'int(dialog_height * 0.12),  # top (below Material)'),
    ('int(dialog_height * 0.28)   # bottom (Planes 上方)', 'int(dialog_height * 0.28)   # bottom (above Planes)'),
    ('int(dialog_width * 0.5),    # left (跳过 h: k: l: 标签)', 'int(dialog_width * 0.5),    # left (skip h: k: l: labels)'),
    ('int(height * 0.05),     # top (去掉顶部标题栏)', 'int(height * 0.05),     # top (remove top title bar)'),
    ('int(width * 0.31),         # right (对话框约占 31% 宽度)', 'int(width * 0.31),         # right (dialog occupies ~31% width)'),
    ('int(width * 0.35),      # right (弹窗大约占 35% 宽度)', 'int(width * 0.35),      # right (dialog occupies ~35% width)'),
    # offset tuples with Chinese
    ('(-25, -2, 20, text_h + 4),    # 小一点的区域', '(-25, -2, 20, text_h + 4),    # slightly smaller region'),
    ('(-30, -5, 25, text_h + 10),   # 紧贴文本左侧', '(-30, -5, 25, text_h + 10),   # tight to the left of text'),
    ('(-50, -5, 45, text_h + 10),   # 稍远一点', '(-50, -5, 45, text_h + 10),   # slightly further'),
    ('(-70, -5, 65, text_h + 10),   # 更远', '(-70, -5, 65, text_h + 10),   # even further'),
]


def apply_replacements(text: str) -> str:
    for zh, en in sorted(REPLACEMENTS, key=lambda x: -len(x[0])):
        text = text.replace(zh, en)
    return text


FILES = [
    'avantage_evaluator.py', 'dm_evaluator.py', 'jade_evaluator.py',
    'ms_evaluator.py', 'vesta_evaluator.py',
    'avantage_evaluate_test.py', 'Jade_evaluate_test.py', 'ms_evaluate_test.py',
    'dm_evaluate_test.py', 'vesta_evaluate_test.py',
]

if __name__ == '__main__':
    for fname in FILES:
        fpath = BASE / fname
        if not fpath.exists():
            continue
        text = fpath.read_text(encoding='utf-8')
        new_text = apply_replacements(text)
        if new_text != text:
            fpath.write_text(new_text, encoding='utf-8')
            print(f'✓ Updated {fname}')
        else:
            print(f'  No changes: {fname}')
    print('\nDone!')
