"""
Second pass: translate all remaining Chinese text in evaluate/ Python files.
Uses a comprehensive replacement dictionary.
"""
import re
from pathlib import Path

BASE = Path(__file__).parent

# ============================================================
# Comprehensive Chinese → English replacements (ordered by length desc)
# ============================================================
REPLACEMENTS = [
    # ---- Log levels ----
    ('"失败"', '"FAIL"'),
    ('"成功"', '"SUCCESS"'),
    # ---- Region names (any remaining) ----
    ('"底部50%"', '"bottom50%"'),
    ('"中心"', '"center"'),
    ('"右下角"', '"bottom-right"'),
    ('"左侧30%"', '"left30%"'),
    ('"左侧50%"', '"left50%"'),
    ('"右侧30%"', '"right30%"'),
    ('"中心区域"', '"center-area"'),
    ('"底部20%"', '"bottom20%"'),
    # region in dict values (single-quoted)
    ("'region': '完整'", "'region': 'full'"),
    ("'region': '中心50%'", "'region': 'center50%'"),
    ("'region': '左侧20%'", "'region': 'left20%'"),
    ("'region': '左侧40%'", "'region': 'left40%'"),
    ("'region':'完整'", "'region':'full'"),
    ("'region':'中心50%'", "'region':'center50%'"),
    ("'region':'左侧20%'", "'region':'left20%'"),
    ("'region':'左侧40%'", "'region':'left40%'"),
    # ---- Error message strings ----
    ('"截图数量不足"', '"Insufficient screenshots"'),
    ('"没有可用的截图"', '"No screenshots available"'),
    ("'error': '参数名称和期望值数量不匹配'", "'error': 'Mismatch between parameter names and expected values count'"),
    # ---- Docstrings ----
    ('"""主函数：生成理论得分 + 运行批量评估 + 生成对比报告"""',
     '"""Main function: generate theoretical scores + run batch evaluation + generate comparison report"""'),
    ('"""从OCR文本中提取VESTA文件名"""', '"""Extract VESTA filename from OCR text"""'),
    ('"""准备参考图片的裁剪版本"""', '"""Prepare cropped version of reference image"""'),
    ('"""判断两个文件名是否匹配（忽略扩展名和大小写）"""',
     '"""Check if two filenames match (ignoring extension and case)"""'),
    ('"""批量运行评估实验"""', '"""Run evaluation experiments in batch"""'),
    ('"""按元素计算准确率矩阵（%）"""', '"""Calculate accuracy matrix (%) by element"""'),
    ('"""检查参数值是否设置正确"""', '"""Check if parameter values are set correctly"""'),
    ('"""检查复选框是否被选中（通过图像分析）"""',
     '"""Check if a checkbox is selected (via image analysis)"""'),
    ('"""检查对话框中的多个字段值"""', '"""Check multiple field values in a dialog"""'),
    ('"""检查截图与参考图片的视觉相似度（带裁剪图像保存）"""',
     '"""Check visual similarity between screenshot and reference image (with cropped image saving)"""'),
    ('"""检查文件是否已打开"""', '"""Check if a file has been opened"""'),
    ('"""检查是否使用了绘图工具（Box, Oval, Profile等）"""',
     '"""Check if a drawing tool (Box, Oval, Profile, etc.) was used"""'),
    ('"""检查是否出现指定标题的对话框"""', '"""Check if a dialog with the specified title appeared"""'),
    ('"""检查标题栏中是否包含指定文件名"""',
     '"""Check if the title bar contains the specified filename"""'),
    ('"""检查框边颜色是否匹配期望颜色"""', '"""Check if the border color matches the expected color"""'),
    ('"""检查缩放操作（检测zoom相关文字或数值）"""',
     '"""Check zoom operation (detect zoom-related text or values)"""'),
    ('"""检查原子删除操作"""', '"""Check atom deletion operation"""'),
    ('"""汇总统计：任务级 + 检查点级"""', '"""Summary statistics: task-level + checkpoint-level"""'),
    ('"""生成字段匹配模式"""', '"""Generate field matching patterns"""'),
    ('"""生成检查点级别的对比报告"""', '"""Generate checkpoint-level comparison report"""'),
    ('"""规范化文件名，去除扩展名"""', '"""Normalize filename, remove extension"""'),
    ('"""计算准确率矩阵"""', '"""Calculate accuracy matrix"""'),
    ('"""计算统计信息"""', '"""Calculate statistics"""'),
    ('"""评估任务"""', '"""Evaluate task"""'),
    ('"""读取accessibility tree文件"""', '"""Read accessibility tree file"""'),
    ('"""预处理:识别所有截图中的信息(文件名、窗口标题等)"""',
     '"""Preprocessing: identify information in all screenshots (filenames, window titles, etc.)"""'),
    # Multi-line docstring starts
    ('"""检查OCR是否识别到特定文本', '"""Check if OCR recognized specific text'),
    # ---- Section comments ----
    ('# ==================== 主函数 ====================', '# ==================== MAIN FUNCTION ===================='),
    ('# ==================== 评估函数 ====================', '# ==================== EVALUATION FUNCTIONS ===================='),
    ('# ============ 主函数 ============', '# ============ MAIN FUNCTION ============'),
    ('# ============ 任务评估主函数 ============', '# ============ MAIN TASK EVALUATION FUNCTION ============'),
    ('# ============ 任务配置 ============', '# ============ TASK CONFIGS ============'),
    ('# ============ 评估函数 ============', '# ============ EVALUATION FUNCTIONS ============'),
    ('# ============ 对比报告生成 ============', '# ============ COMPARISON REPORT GENERATION ============'),
    ('# ============ 批量评估运行器 ============', '# ============ BATCH EVALUATION RUNNER ============'),
    ('# ============ 理论得分矩阵生成 ============', '# ============ THEORETICAL SCORE MATRIX GENERATION ============'),
    ('# ============ 理论得分计算 (修复版) ============', '# ============ THEORETICAL SCORE CALCULATION (Fixed) ============'),
    ('# ============ 理论得分计算 ============', '# ============ THEORETICAL SCORE CALCULATION ============'),
    ('# ============= 新增：检查所有颜色的匹配度 =============', '# ============= NEW: check all color match ratios ============='),
    ('# ============= 颜色分析结束 =============', '# ============= Color analysis end ============='),
    ('# === 兜底逻辑: 仅在未指定特定目标时生效 ===', '# === Fallback logic: only applies when no specific target is specified ==='),
    ('# === 步骤1: 在顶部 5% 检测弹窗标题 ===', '# === Step 1: Detect dialog title in top 5% ==='),
    ('# === 步骤1: 找到检测到文件名的第一帧 ===', '# === Step 1: Find the first frame where a filename is detected ==='),
    ('# === 步骤1: 检测弹窗标题 ===', '# === Step 1: Detect dialog title ==='),
    ('# === 步骤1: 检测绿色角点 ===', '# === Step 1: Detect green corners ==='),
    ('# === 步骤2: 在完整区域检测字段内容 ===', '# === Step 2: Detect field content in full region ==='),
    ('# === 步骤2: 在完整区域统计目标文本出现次数 ===', '# === Step 2: Count target text occurrences in full region ==='),
    ('# === 步骤2: 在左 40%，上 60% 区域检测字段内容 ===', '# === Step 2: Detect field content in left 40%, top 60% region ==='),
    ('# === 步骤2: 检查初始状态 (文件打开后的第一帧) ===', '# === Step 2: Check initial state (first frame after file open) ==='),
    ('# === 步骤2: 检查框内部是否填充了目标颜色 ===', '# === Step 2: Check if box interior is filled with target color ==='),
    ('# === 步骤3: 判断是否匹配 ===', '# === Step 3: Determine if match ==='),
    ('# === 步骤3: 检查最终状态 (最后一帧) ===', '# === Step 3: Check final state (last frame) ==='),
    ('# === 步骤4: 判定逻辑 ===', '# === Step 4: Decision logic ==='),
    ('# === 辅助函数: 检测左下角20%区域是否有a,b,c标签 ===',
     '# === Helper: detect if a,b,c labels exist in bottom-left 20% region ==='),
    ('# ===== 策略0: 连写形式 =====', '# ===== Strategy-0: Concatenated form ====='),
    ('# ===== 策略1: 标准格式（带点号）=====', '# ===== Strategy-1: Standard format (with dots) ====='),
    ('# ===== 策略2: 不带扩展名 =====', '# ===== Strategy-2: Without extension ====='),
    ('# ===== 策略3: 模糊匹配 =====', '# ===== Strategy-3: Fuzzy matching ====='),
    ('# ========== 1. 生成检查点级别对比表 ==========', '# ========== 1. Generate checkpoint-level comparison table =========='),
    ('# ========== 2. 生成总分矩阵对比 Excel ==========', '# ========== 2. Generate total score matrix comparison Excel =========='),
    ('# ========== 3. 打印统计信息 ==========', '# ========== 3. Print statistics =========='),
    # Checkpoint comments
    ('# === 检查点10: 坐标轴切换 ===', '# === Checkpoint 10: Axis switching ==='),
    ('# === 检查点11: 对话框打开 ===', '# === Checkpoint 11: Dialog open ==='),
    ('# === 检查点12: Polyhedral样式 ===', '# === Checkpoint 12: Polyhedral style ==='),
    ('# === 检查点13: Orientation向量 ===', '# === Checkpoint 13: Orientation vector ==='),
    ('# === 检查点14: 晶面 ===', '# === Checkpoint 14: Crystal plane ==='),
    ('# === 检查点15: Boundary设置 ===', '# === Checkpoint 15: Boundary settings ==='),
    ('# === 检查点16: Bonds清空 ===', '# === Checkpoint 16: Bonds cleared ==='),
    ('# === 检查点17: 原子坐标 ===', '# === Checkpoint 17: Atom coordinates ==='),
    ('# === 检查点18: 多个晶面 ===', '# === Checkpoint 18: Multiple crystal planes ==='),
    ('# === 检查点1: 文件导入 ===', '# === Checkpoint 1: File import ==='),
    ('# === 检查点1: 文件打开 ===', '# === Checkpoint 1: File open ==='),
    ('# === 检查点2: 图像放大缩小 ===', '# === Checkpoint 2: Image zoom in/out ==='),
    ('# === 检查点2: 对话框标题 ===', '# === Checkpoint 2: Dialog title ==='),
    ('# === 检查点2: 标准取向 ===', '# === Checkpoint 2: Standard orientation ==='),
    ('# === 检查点3: 关键词检查 (修复版) ===', '# === Checkpoint 3: Keyword check (Fixed) ==='),
    ('# === 检查点3: 堆叠图 ===', '# === Checkpoint 3: Stacked graph ==='),
    ('# === 检查点3: 旋转90度 ===', '# === Checkpoint 3: Rotate 90 degrees ==='),
    ('# === 检查点4: 字段值检查 (修复版) ===', '# === Checkpoint 4: Field value check (Fixed) ==='),
    ('# === 检查点4: 平移 ===', '# === Checkpoint 4: Translation ==='),
    ('# === 检查点4: 重复文件 ===', '# === Checkpoint 4: Duplicate files ==='),
    ('# === 检查点5: 背景添加 ===', '# === Checkpoint 5: Background addition ==='),
    ('# === 检查点5: 视觉相似度 ===', '# === Checkpoint 5: Visual similarity ==='),
    ('# === 检查点5: 风格切换 ===', '# === Checkpoint 5: Style switching ==='),
    ('# === 检查点6: 原子信息对话框 ===', '# === Checkpoint 6: Atom info dialog ==='),
    ('# === 检查点6: 多字段检查 ===', '# === Checkpoint 6: Multi-field check ==='),
    ('# === 检查点6: 对话框存在 ===', '# === Checkpoint 6: Dialog exists ==='),
    ('# === 检查点7: 原子删除 ===', '# === Checkpoint 7: Atom deletion ==='),
    ('# === 检查点7: 对话框参数 ===', '# === Checkpoint 7: Dialog parameters ==='),
    ('# === 检查点8: 能量轴反向 ===', '# === Checkpoint 8: Energy axis reversed ==='),
    ('# === 检查点8: 键显示 ===', '# === Checkpoint 8: Bond display ==='),
    ('# === 检查点9: 文件复制 ===', '# === Checkpoint 9: File copy ==='),
    ('# === 检查点9: 缩放 ===', '# === Checkpoint 9: Zoom ==='),
    # DM section comments
    ('# ── 1. 文件导入 ──────────────────────────────────────────────',
     '# ── 1. File import ──────────────────────────────────────────────'),
    ('# ── 10. 填充 Box ──────────────────────────────────────────────',
     '# ── 10. Fill Box ──────────────────────────────────────────────'),
    ('# ── 11. 弹窗文本计数 ──────────────────────────────────────────',
     '# ── 11. Popup text count ──────────────────────────────────────────'),
    ('# ── 2. OCR 文本检测 ──────────────────────────────────────────',
     '# ── 2. OCR text detection ──────────────────────────────────────────'),
    ('# ── 3. 绘图工具 ──────────────────────────────────────────────',
     '# ── 3. Drawing tool ──────────────────────────────────────────────'),
    ('# ── 4. 框边颜色 ──────────────────────────────────────────────',
     '# ── 4. Border color ──────────────────────────────────────────────'),
    ('# ── 5. 文本颜色 ──────────────────────────────────────────────',
     '# ── 5. Text color ──────────────────────────────────────────────'),
    ('# ── 6. 复选框 ────────────────────────────────────────────────',
     '# ── 6. Checkbox ────────────────────────────────────────────────'),
    ('# ── 7. Data Bar 文本特征 ──────────────────────────────────────',
     '# ── 7. Data Bar text features ──────────────────────────────────────'),
    ('# ── 8. ROI 复制放大 ───────────────────────────────────────────',
     '# ── 8. ROI copy & enlarge ───────────────────────────────────────────'),
    ('# ── 9. 弹窗检测（含字段检查）────────────────────────────────',
     '# ── 9. Dialog detection (with field check) ────────────────────────────────'),
    ('# ── 关键修改：对参考图也进行相同比例的裁剪 ──',
     '# ── Key change: apply the same crop ratio to the reference image ──'),
    ('# ── 总分矩阵报告 ──────────────────────────────────────────────',
     '# ── Total score matrix report ──────────────────────────────────────────'),
    ('# ── 文本颜色从无到有 ──────────────────────────────────────────',
     '# ── Text color: from none to some ──────────────────────────────────────────'),
    ('# ── 未知检查点 ────────────────────────────────────────────────',
     '# ── Unknown checkpoint ────────────────────────────────────────────'),
    ('# ── 检查点明细报告 ────────────────────────────────────────────',
     '# ── Checkpoint detail report ────────────────────────────────────────────'),
    ('# ── 步骤 1：理论得分 ──────────────────────────────────────────',
     '# ── Step 1: Theoretical scores ──────────────────────────────────────────'),
    ('# ── 步骤 2：批量实际评估 ──────────────────────────────────────',
     '# ── Step 2: Batch actual evaluation ──────────────────────────────────────────'),
    ('# ── 步骤 3：对比报告 ──────────────────────────────────────────',
     '# ── Step 3: Comparison report ──────────────────────────────────────────'),
    # ---- General comments ----
    ('# ✅ 保存调试图像（可选）', '# ✅ Save debug image (optional)'),
    ('# ✅ 修改：读取完整区域而不是局部区域', '# ✅ Change: read full region instead of partial region'),
    ('# ✅ 改进：在文本左侧更大范围内搜索复选框', '# ✅ Improvement: search for checkbox in a larger range to the left of text'),
    ('# ✅ 裁剪区域：去掉顶部15%、底部15%、右侧50%', '# ✅ Crop region: remove top 15%, bottom 15%, right 50%'),
    ('# 不要break，继续检查这个截图中的其他文本检测结果',
     '# Do not break; continue checking other text detection results in this screenshot'),
    ('# 严格模式：数量必须相等 + 所有文件都匹配',
     '# Strict mode: count must be equal + all files match'),
    ('# 为所有任务记录错误', '# Record errors for all tasks'),
    ('# 为纯数字添加变体', '# Add variants for pure numbers'),
    ('# 也检查空格替换为下划线后的版本', '# Also check the version with spaces replaced by underscores'),
    ('# 二值化', '# Binarization'),
    ('# 从文件名中提取dm+数字部分', '# Extract dm+number part from filename'),
    ('# 从这行中提取数字', '# Extract numbers from this line'),
    ('# 任务配置中的使用方法:', '# Usage in task config:'),
    ('# 使用 \\w* 允许匹配到误识别的字母，如 FeO-Feo',
     '# Use \\w* to allow matching misrecognized letters, e.g. FeO-Feo'),
    ('# 使用 pytesseract 进行 OCR', '# Use pytesseract for OCR'),
    ('# 使用OCR定位文本', '# Use OCR to locate text'),
    ('# 使用单词边界确保精确匹配', '# Use word boundaries to ensure exact matching'),
    ('# 使用定义的颜色范围检测每种颜色的匹配像素数', '# Use defined color ranges to count matching pixels for each color'),
    ('# 使用更宽松的匹配：不区分大小写，允许前后有任意字符',
     '# Use looser matching: case-insensitive, allow any surrounding characters'),
    ('# 使用正则表达式确保是独立的单词（避免匹配 "nm" 在 "anm" 中）',
     '# Use regex to ensure it is an isolated word (avoid matching "nm" inside "anm")'),
    ('# 例如: 1.5, 1.51, 1.5I, 1.5l, 1.5|, 1.5i, 1.56 等',
     '# e.g.: 1.5, 1.51, 1.5I, 1.5l, 1.5|, 1.5i, 1.56 etc.'),
    ('# 保存实际得分', '# Save actual scores'),
    ('# 保存实际得分详细信息（JSON）', '# Save actual score details (JSON)'),
    ('# 保存理论得分', '# Save theoretical scores'),
    ('# 保存理论得分详细信息（JSON）', '# Save theoretical score details (JSON)'),
    ('# 保存结果', '# Save results'),
    ('# 保存结果到details中', '# Save results to details'),
    ('# 保存裁剪区域用于调试', '# Save cropped region for debugging'),
    ('# 保存裁剪后的图片', '# Save cropped image'),
    ('# 保存角点掩码调试图', '# Save corner mask debug image'),
    ('# 保存详细结果', '# Save detailed results'),
    ('# 保存调试图', '# Save debug image'),
    ('# 保存调试图像', '# Save debug image'),
    ('# 保存调试图（未找到符合条件的情况）', '# Save debug image (no match found case)'),
    ('# 保存错误日志', '# Save error log'),
    ('# 保存预处理后的图像', '# Save preprocessed image'),
    ('# 保存颜色掩码调试图', '# Save color mask debug image'),
    ('# 保存黄色掩码', '# Save yellow mask'),
    ('# 保存：保存的是当前截图的裁剪结果（参考图裁剪只用于计算，不保存）',
     '# Save: saving the crop of the current screenshot (reference image crop is for calculation only, not saved)'),
    ('# 保持原始value,只转小写用于不区分大小写匹配',
     '# Keep original value, only lowercase for case-insensitive matching'),
    ('# 修复：每种视觉参考必须同时满足多个conditions',
     '# Fix: each visual reference must satisfy multiple conditions simultaneously'),
    ('# 先在规范化文本中搜索', '# First search in normalized text'),
    ('# 先尝试精确匹配', '# First try exact matching'),
    ('# 先尝试精确匹配（完全相等）', '# First try exact matching (fully equal)'),
    ('# 先检查是否是Search/Match Display弹窗', '# First check if it is a Search/Match Display dialog'),
    ('# 先规范化再解析', '# Normalize first, then parse'),
    ('# 关键改进：调整顺序，把短的、容易被误匹配的放在前面检查',
     '# Key improvement: reorder to check shorter, easily mismatched items first'),
    ('# 关键词匹配的多种可能', '# Multiple possible keyword matches'),
    ('# 内部函数：检查框边颜色匹配', '# Inner function: check border color match'),
    ('# 再在原始文本中搜索', '# Then search in original text'),
    ('# 写入调试文件', '# Write to debug file'),
    ('# 几何形状检查', '# Geometry check'),
    ('# 分析峰数量变化', '# Analyze peak count change'),
    ('# 创建评估器', '# Create evaluator'),
    ('# 初始化结果存储', '# Initialize result storage'),
    ('# 初始化该轨迹的详细得分字典', '# Initialize detailed score dict for this trajectory'),
    ('# 判定对话框是否在当前帧', '# Determine if dialog is in current frame'),
    ('# 判定条件：必须看到过 "zoom in" 且当前步骤数值为 100',
     '# Decision condition: must have seen "zoom in" and current step value is 100'),
    ('# 判定：检测到3个或以上的Axes特有菜单项 → 菜单已展开',
     '# Decision: 3+ Axes-specific menu items detected → menu is expanded'),
    ('# 判断是否匹配', '# Determine if matched'),
    ('# 判断是否满足条件', '# Determine if conditions are met'),
    ('# 判断最佳匹配是否表示选中', '# Determine if the best match indicates selection'),
    ('# 判断最可能的颜色', '# Determine the most likely color'),
    ('# 判断标准：Y方向位移 > 原ROI高度的30%',
     '# Decision criterion: Y displacement > 30% of original ROI height'),
    ('# 加载参考图片配置', '# Load reference image configuration'),
    ('# 加载图像', '# Load image'),
    ('# 动态导入JadeEvaluator', '# Dynamically import JadeEvaluator'),
    ('# 包含模式：只要包含所有期望文件即可', '# Inclusion mode: just need to contain all expected files'),
    ('# 匹配 "数值 + 可选的单个干扰字符"', '# Match "value + optional single noise character"'),
    ('# 匹配: 0.000000, 1.000000, 0.500000 等（6位小数）',
     '# Match: 0.000000, 1.000000, 0.500000 etc. (6 decimal places)'),
    ('# 匹配: XRDAxrdml, XRD4xrdml, XRD1xrdml 等', '# Match: XRDAxrdml, XRD4xrdml, XRD1xrdml etc.'),
    ('# 匹配关键词', '# Match keywords'),
    ('# 匹配形如 "数字 + nm" 的模式', '# Match patterns like "number + nm"'),
    ('# 匹配数据行：以数字开头（行号）', '# Match data rows: starting with a number (row index)'),
    ('# 匹配模式: Ga0, Ga1, N2, N3 等', '# Match pattern: Ga0, Ga1, N2, N3 etc.'),
    ('# 匹配模式: x(min) = 数字 或 xmin = 数字', '# Match pattern: x(min) = number or xmin = number'),
    ('# 单层列表（旧格式兼容）', '# Single-level list (legacy format compatibility)'),
    ('# 去掉 check_ 前缀', '# Remove check_ prefix'),
    ('# 去掉扩展名后做宽松匹配', '# Do loose matching after removing extension'),
    ('# 去掉扩展名进行比较', '# Remove extension for comparison'),
    ('# 去除尾部的点和空格，转小写', '# Remove trailing dots and spaces, lowercase'),
    ('# 去除常见扩展名', '# Remove common extensions'),
    ('# 去除扩展名', '# Remove extension'),
    ('# 取前三个数字作为 h, k, l', '# Take first three numbers as h, k, l'),
    ('# 只匹配化学式或文件名,不匹配文档类型', '# Only match chemical formulas or filenames, not document types'),
    ('# 只有"找到了必须关键词 且 没找到任何禁止关键词"才算通过',
     '# Only pass when "required keywords found AND no forbidden keywords found"'),
    ('# 只有当关键词长度>=7时才允许部分匹配', '# Only allow partial matching when keyword length >= 7'),
    ('# 只检查参数名存在（如Iterations, C1s Scan等）', '# Only check if parameter name exists (e.g. Iterations, C1s Scan)'),
    ('# 只计入imported_files，因为这是主要操作的文件',
     '# Only count imported_files, as these are the primarily operated files'),
    ('# 向内缩进一点的点', '# Point slightly inset from the border'),
    ('# 向后收集数值（使用清理后的文本）', '# Collect values going forward (using cleaned text)'),
    ('# 因为 dml 归一化后变成 dm1', '# Because dml becomes dm1 after normalization'),
    ('# 图像预处理', '# Image preprocessing'),
    ('# 在 OCR 文本中查找对应的值', '# Find the corresponding value in OCR text'),
    ('# 在值匹配部分添加（针对 80 的误识别）：', '# Added to value matching (for misrecognition of 80):'),
    ('# 在图上标注检测到的框边颜色', '# Annotate detected border color on the image'),
    ('# 在字段匹配部分添加：', '# Added to field matching:'),
    ('# 在弹窗内部裁剪 Polyhedral style 区域', '# Crop Polyhedral style region inside the dialog'),
    ('# 在调试图上标记中心点和轮廓', '# Mark center point and contour on debug image'),
    ('# 基于颜色相似度的聚类', '# Clustering based on color similarity'),
    ('# 基本尺寸检查', '# Basic size check'),
    ('# 基础分：对话框打开', '# Base score: dialog opened'),
    ('# 填充阈值：> 80% 表示已填充', '# Fill threshold: > 80% means filled'),
    ('# 处理 field_name 为 None 的情况', '# Handle case where field_name is None'),
    ('# 多层列表：每个小list是一种可能状态', '# Multi-level list: each sub-list is one possible state'),
    ('# 失败汇总输出', '# Failure summary output'),
    ('# 失败诊断', '# Failure diagnosis'),
    ('# 如果不在映射中，返回基本变体', '# If not in mapping, return basic variant'),
    ('# 如果不是列表，转换为列表', '# If not a list, convert to list'),
    ('# 如果严格匹配失败，尝试更宽松的匹配', '# If strict matching fails, try looser matching'),
    ('# 如果之前见过对话框，现在消失了', '# If dialog was seen before and now disappeared'),
    ('# 如果已经找到了一些坐标，但遇到非数值行，可能是表格分隔',
     '# If some coordinates already found but encounter non-numeric line, likely table separator'),
    ('# 如果已经找到表头，开始查找数据行', '# If header already found, start looking for data rows'),
    ('# 如果当前帧匹配的文件数量比之前的记录多，更新"最佳记录"以便调试',
     '# If current frame matched more files than previous record, update "best record" for debugging'),
    ('# 如果当前帧没有找齐所有文件，直接跳过，看下一帧',
     '# If current frame did not find all files, skip and move to next frame'),
    ('# 如果所有参数都找到了，提前返回', '# If all parameters found, return early'),
    ('# 如果所有设置都匹配', '# If all settings match'),
    ('# 如果找到最佳矩形，检查得分是否达到阈值', '# If best rectangle found, check if score reaches threshold'),
    ('# 如果未裁剪过，则裁剪', '# If not yet cropped, crop now'),
    ('# 如果没找到，返回规范化的key', '# If not found, return normalized key'),
    ('# 如果没有字段名,只匹配值本身', '# If no field name, only match value itself'),
    ('# 如果没有字段检查要求，直接返回成功', '# If no field check required, return success directly'),
    ('# 如果没有指定目标，只要发现任何格式正确的键就通过',
     '# If no target specified, pass as long as any correctly-formatted key is found'),
    ('# 如果没有提供expected_value，只检查参数名存在',
     '# If expected_value not provided, only check that parameter name exists'),
    ('# 如果没有预定义的变体，使用精确匹配', '# If no predefined variants, use exact matching'),
    ('# 如果没有预定义，生成基本变体', '# If no predefined, generate basic variants'),
    ('# 如果没检测到文件名，使用第一帧', '# If no filename detected, use the first frame'),
    ('# 如果精确匹配失败，再尝试部分匹配', '# If exact match fails, try partial matching'),
    ('# 如果精确匹配失败，尝试模糊匹配（针对浮点数 + 鼠标光标干扰）',
     '# If exact match fails, try fuzzy matching (for floating point + cursor interference)'),
    ('# 如果至少匹配到一个目标文本，则认为成功', '# If at least one target text matched, consider success'),
    ('# 如果这个参数已经找到过，跳过', '# If this parameter was already found, skip'),
    ('# 如果遍历完所有截图都没有完全匹配', '# If all screenshots traversed without a complete match'),
    ('# 如果颜色占比超过阈值，认为匹配', '# If color ratio exceeds threshold, consider match'),
    ('# 子串匹配（双向）', '# Substring matching (bidirectional)'),
    ('# 子串匹配', '# Substring matching'),
    ('# 字段名也可能有 OCR 误识别', '# Field name may also have OCR misrecognition'),
    ('# 字段检查：每个字段 0/1，取最严格 —— 全部满足才得 1',
     '# Field check: each field 0/1, strictest — all must be satisfied to get 1'),
    ('# 存储规范化文本到实例变量', '# Store normalized text to instance variable'),
    ('# 完整匹配（不区分大小写）', '# Full match (case-insensitive)'),
    ('# 定义 Data Bar 的特征文本模式', '# Define Data Bar characteristic text patterns'),
    ('# 定义参数名的常见OCR变体', '# Define common OCR variants of parameter names'),
    ('# 定义变体映射', '# Define variant mapping'),
    ('# 定义各 OCR 目标对应的轨迹操作标记', '# Define trajectory operation tags for each OCR target'),
    ('# 定义弹窗标题的常见OCR变体', '# Define common OCR variants of dialog titles'),
    ('# 定义所有可能的文件名及其变体', '# Define all possible filenames and their variants'),
    ('# 定义绿色的 HSV 范围', '# Define HSV range for green'),
    ('# 定义颜色的HSV范围', '# Define HSV range for colors'),
    ('# 定义颜色范围', '# Define color ranges'),
    ('# 实时打印 - 包含裁剪图像路径', '# Real-time print - includes cropped image path'),
    ('# 实时打印', '# Real-time print'),
    ('# 宽高比检查', '# Aspect ratio check'),
    ('# 对于 "20 nm"，分别尝试匹配 "20nm", "20 nm", "2onm" 等变体',
     '# For "20 nm", try matching variants like "20nm", "20 nm", "2onm" etc.'),
    ('# 对参考图也用相同比例裁剪（假设参考图比例相似）',
     '# Crop reference image with same ratio (assuming similar proportions)'),
    ('# 对当前截图裁剪', '# Crop current screenshot'),
    ('# 对齐检查点数量（以理论为准）', '# Align checkpoint counts (use theoretical as reference)'),
    ('# 对齐检查点数量', '# Align checkpoint counts'),
    ('# 对齐长度', '# Align length'),
    ('# 导入 DM 任务配置', '# Import DM task configs'),
    ('# 导入AvantageEvaluator', '# Import AvantageEvaluator'),
    ('# 导入VESTAEvaluator', '# Import VESTAEvaluator'),
    ('# 导入任务配置', '# Import task configs'),
    ('# 导入原有的VESTAEvaluator', '# Import the VESTAEvaluator'),
    ('# 将 o 和 O 替换为 0', '# Replace o and O with 0'),
    ('# 小数点的变体', '# Decimal point variants'),
    ('# 尝试匹配: 字段名 + 分隔符 + 数值', '# Try matching: field name + separator + value'),
    ('# 尝试匹配任意一种可能的状态', '# Try matching any possible state'),
    ('# 尝试匹配弹窗标题的各种变体', '# Try matching various dialog title variants'),
    ('# 尝试匹配所有可能的期望值', '# Try matching all possible expected values'),
    ('# 尝试匹配每个文件名', '# Try matching each filename'),
    ('# 尝试多个可能的位置和大小', '# Try multiple possible positions and sizes'),
    ('# 尝试多种可能的格式', '# Try multiple possible formats'),
    ('# 尝试所有4个角点的组合', '# Try all 4 corner combinations'),
    ('# 尝试提取zoom数值', '# Try to extract zoom value'),
    ('# 尺寸检查', '# Size check'),
    ('# 尺寸统一：resize 参考裁剪图匹配当前截图裁剪尺寸（或反过来都行）',
     '# Unify size: resize reference crop to match current screenshot crop size (or vice versa)'),
    ('# 尿素球棍模型：需要同时有 display_style_ball_stick 且是 urea',
     '# Urea ball-and-stick model: requires both display_style_ball_stick and urea'),
    ('# 左下20%区域', '# Bottom-left 20% region'),
    ('# 常见参数名的OCR变体映射', '# OCR variant mapping for common parameter names'),
    ('# 延迟导入，避免循环依赖', '# Lazy import to avoid circular dependency'),
    ('# 弹窗打开操作标记', '# Dialog open operation flag'),
    ('# 归一化OCR文本', '# Normalize OCR text'),
    ('# 归一化检测到的文本', '# Normalize detected text'),
    ('# 归一化目标文本（用于匹配）', '# Normalize target text (for matching)'),
    ('# 形态学操作：去噪点', '# Morphological operation: remove noise'),
    ('# 形态学操作：去除噪点', '# Morphological operation: remove noise'),
    ('# 形态学操作', '# Morphological operation'),
    ('# 快速匹配', '# Quick match'),
    ('# 总分矩阵', '# Total score matrix'),
    ('# 总分级别统计', '# Score-level statistics'),
    ('# 成功找到', '# Successfully found'),
    ('# 成功条件：', '# Success condition:'),
    ('# 或:   "3     1    1    0    2.76169"', '# Or: "3     1    1    0    2.76169"'),
    ('# 或者直接检查是否有Figure of Merit列（说明有匹配结果）',
     '# Or directly check if Figure of Merit column exists (indicates match results)'),
    ('# 所有可能状态都不匹配', '# No possible state matches'),
    ('# 打印OCR文本预览用于调试', '# Print OCR text preview for debugging'),
    ('# 打印RGB和HSV值', '# Print RGB and HSV values'),
    ('# 打印所有颜色的匹配度（按比例从高到低排序）',
     '# Print all color match ratios (sorted by ratio, high to low)'),
    ('# 打印所有颜色的匹配度', '# Print all color match ratios'),
    ('# 打印未找到的参数', '# Print unfound parameters'),
    ('# 打印统计信息', '# Print statistics'),
    ('# 打印统计', '# Print statistics'),
    ('# 扩大 OCR 范围到顶部和底部，因为 "zoom in" 可能出现在状态栏',
     '# Expand OCR range to top and bottom, as "zoom in" may appear in status bar'),
    ('# 扩展边界框以确保包含文本', '# Expand bounding box to ensure text is included'),
    ('# 找到了弹窗但字段不匹配，给部分分', '# Dialog found but fields do not match, give partial score'),
    ('# 找到最大的黄色区域（应该是选中的样式）', '# Find the largest yellow region (should be the selected style)'),
    ('# 找到标题了', '# Title found'),
    ('# 按行分析表格', '# Analyze table row by row'),
    ('# 按行分析', '# Analyze row by row'),
    ('# 提取区域', '# Extract region'),
    ('# 提取坐标和HSV', '# Extract coordinates and HSV'),
    ('# 提取峰数量', '# Extract peak count'),
    ('# 提取所有文本', '# Extract all text'),
    ('# 提取文本区域', '# Extract text region'),
    ('# 提取框内部区域（向内缩进一点，避免边框干扰）',
     '# Extract box interior region (slightly inset to avoid border interference)'),
    ('# 提取检查点结果', '# Extract checkpoint results'),
    ('# 数字的OCR常见错误', '# Common OCR errors for digits'),
    ('# 数值越大越相似（1表示完全相同）', '# Higher value means more similar (1 = identical)'),
    ('# 方案一：直接查看是否有两种截图中出现了'
     , '# Option 1: directly check if two screenshots show'),
    ('# 方框的内部区域（向内缩进5%）', '# Box interior region (5% inset)'),
    ('# 有效的边界框', '# Valid bounding box'),
    ('# 检查 Mask 复选框是否被选中', '# Check if Mask checkbox is selected'),
    ('# 检查Shirley', '# Check Shirley'),
    ('# 检查弹窗参数', '# Check dialog parameters'),
    ('# 检查框边是否包含颜色', '# Check if border contains color'),
    ('# 检查最后一帧中是否检测到同样多的文件', '# Check if same number of files detected in last frame'),
    ('# 第一个步骤对应初始状态', '# First step corresponds to initial state'),
    ('# 简单相似度计算', '# Simple similarity calculation'),
    ('# 统一大小写', '# Normalize case'),
    ('# 统计各项得分', '# Count scores for each item'),
    ('# 获取所有文件：主要文件 + 其他文件', '# Get all files: primary files + other files'),
    ('# 获取参数名的常见OCR变体', '# Get common OCR variants of parameter names'),
    ('# 获取文件名的所有可能变体', '# Get all possible variants of a filename'),
    ('# 获取期望值的常见OCR变体', '# Get common OCR variants of expected values'),
    ('# 获取全图文本，规范化处理', '# Get full image text with normalization'),
    ('# 获取文件名的所有可能变体', '# Get all possible filename variants'),
    ('# 获取期望文件名的变体列表', '# Get variant list for expected filename'),
    ('# 调试输出', '# Debug output'),
    ('# 评估结果', '# Evaluation result'),
    ('# 识别到的文件', '# Identified files'),
    ('# 通过检测 "Reverse Energy Axis" 弹窗或选项',
     '# Detected via "Reverse Energy Axis" dialog or option'),
    ('# 错误处理', '# Error handling'),
    ('# 颜色名称的变体', '# Color name variants'),
    ('# 验证参数和值的数量匹配（仅在需要检查值时）',
     '# Verify parameter count matches value count (only when value check is needed)'),
    ('# 逐行检查，每行只计数一次', '# Check line by line, count each line at most once'),
    ('# 锁定对话框不需要检查这个', '# Lock dialog does not need this check'),
    ('# 默认返回规范化的标准文件名', '# Default: return normalized standard filename'),
    ('# 面间距表格的列名', '# Column names of the d-spacing table'),
    ('# OCR recognition完整区域（菜单可能在任何位置）',
     '# OCR recognition: full region (menu may be anywhere)'),
    ('# OCR recognition中心区域', '# OCR recognition: center region'),
    ('# OCR 识别表格内容', '# OCR: recognize table content'),
    ('# OCR 识别', '# OCR recognition'),
    ('# OCR 配置：允许识别数字、负号和字母 O', '# OCR config: allow digits, minus sign, and letter O'),
    ('# Sheet 1: 总分对比（汇总）', '# Sheet 1: Total score comparison (summary)'),
    ('# Sheet 2-N: 每个任务的检查点详细对比', '# Sheet 2-N: Checkpoint detail comparison for each task'),
    ('# Sheet N+1: 统计摘要', '# Sheet N+1: Statistical summary'),
    ('# Sheet1: 总分对比（宽表）', '# Sheet1: Total score comparison (wide table)'),
    ('# Sheet2+: 每个任务的检查点明细', '# Sheet2+: Checkpoint details for each task'),
    ('# Axes菜单特有的选项', '# Options specific to the Axes menu'),
    ('# H2O：需要同时添加了O和H原子并设置了球棍模型',
     '# H2O: requires both O and H atoms added and ball-and-stick model set'),
    ('# Excel sheet名称限制为31字符', '# Excel sheet names are limited to 31 characters'),
    ('# WRT系列文件 - 匹配 WRT-ZSX-5 或其变体', '# WRT series files - match WRT-ZSX-5 or its variants'),
    ('# XRD系列文件 - 匹配 XRD + 数字（1-4）', '# XRD series files - match XRD + digit (1-4)'),
    ('# X轴选项（Axes菜单特有）', '# X-axis options (specific to Axes menu)'),
    ('# Y轴选项（Axes菜单特有）', '# Y-axis options (specific to Axes menu)'),
    ('# other_files 支持多种可能的状态：', '# other_files supports multiple possible states:'),
    ('# # 方法2: 子串匹配 (检查value是否出现在任何operation中)',
     '# # Method 2: substring matching (check if value appears in any operation)'),
    ('# - 横向：对话框左侧 3% 到 右侧 90%（不包含右侧按钮区域）',
     '# - Horizontal: 3% from left to 90% from left of dialog (excluding right button area)'),
    ('# - 纵向：对话框高度的 62% 到 78%（表格头和数据行）',
     '# - Vertical: 62% to 78% of dialog height (table header and data rows)'),
    # log messages
    ('self._log("开始预处理：识别所有截图中的文件名...", "INFO")',
     'self._log("Starting preprocessing: identifying filenames in all screenshots...", "INFO")'),
    ('self._log("检查能量轴反向", "INFO")', 'self._log("Checking energy axis reversal", "INFO")'),
    ('self._log("检查能量轴反向", "INFO")', 'self._log("Checking energy axis reversal", "INFO")'),
    ('self._log(f"开始评估: {task_name}", "INFO")', 'self._log(f"Starting evaluation: {task_name}", "INFO")'),
    ('self._log(f"识别到 {len(unique_files)} 个不同的文件:", "DEBUG")',
     'self._log(f"Identified {len(unique_files)} distinct files:", "DEBUG")'),
    ('self._log(f"调试信息：所有预处理识别的文件", "DEBUG")',
     'self._log(f"Debug: all files identified in preprocessing", "DEBUG")'),
    ('self._log(f"总共 {len(self.screenshot_files)} 帧截图", "DEBUG")',
     'self._log(f"Total {len(self.screenshot_files)} screenshot frames", "DEBUG")'),
    # f-string log messages
    ('f"  步骤 [{i:02d}]: Binding Energy 计数: {binding_energy_count} (期望: {expected_count})"',
     'f"  Step [{i:02d}]: Binding Energy count: {binding_energy_count} (expected: {expected_count})"'),
    ('f"  步骤 [{i:02d}]: Binding Energy 计数: {binding_energy_count} (期望: {expected_copies})"',
     'f"  Step [{i:02d}]: Binding Energy count: {binding_energy_count} (expected: {expected_copies})"'),
    ('f"  步骤 [{i:02d}]: 在OCR中找到 {max_count} 行包含 \'{matched_variant}\' (期望 {expected_copies})"',
     'f"  Step [{i:02d}]: Found {max_count} lines containing \'{matched_variant}\' in OCR (expected {expected_copies})"'),
    ('f"\\n评估完成: {task_result[\'total_score\']}/{task_result[\'max_score\']} "',
     'f"\\nEvaluation complete: {task_result[\'total_score\']}/{task_result[\'max_score\']} "'),
    # print statements
    ("parser.add_argument('folder', type=str, help='截图文件夹路径')",
     "parser.add_argument('folder', type=str, help='Path to screenshot folder')"),
    ("parser.add_argument('task', type=str, help='任务名称')",
     "parser.add_argument('task', type=str, help='Task name')"),
    ("print(f'\\n可用任务:')", "print(f'\\nAvailable tasks:')"),
    ("print(f'✓ 任务: {args.task}\\n')", "print(f'✓ Task: {args.task}\\n')"),
    ("print(f'✓ 文件夹: {folder_path}')", "print(f'✓ Folder: {folder_path}')"),
    ("print(f'❌ 未找到任务 \\'{args.task}\\'')", "print(f'❌ Task not found: \\'{args.task}\\'')"),
    ("print(f'❌ 错误: {str(e)}')", "print(f'❌ Error: {str(e)}')"),
    ("print(f'❌ 错误: 文件夹不存在: {folder_path}')", "print(f'❌ Error: folder does not exist: {folder_path}')"),
    ("print(f'得分: {result[\"total_score\"]}/{result[\"max_score\"]} ({result[\"pass_rate\"]})')",
     "print(f'Score: {result[\"total_score\"]}/{result[\"max_score\"]} ({result[\"pass_rate\"]})')"),
    ("print(f'评估完成!')", "print(f'Evaluation complete!')"),
    # avantage log messages (formatted)
    ('f"  步骤 [{i:02d}]: ✓ 成功识别到背景类型文本 \'{bg_type}\'"',
     'f"  Step [{i:02d}]: ✓ Successfully identified background type text \'{bg_type}\'"'),
    ('f"  步骤 [{i:02d}]: 发现对话框 \'{title}\'"',
     'f"  Step [{i:02d}]: Dialog found \'{title}\'"'),
    ('f"  步骤 [{i:02d}]: 在 {region} 区域发现弹窗 \'{dialog_title}\'"',
     'f"  Step [{i:02d}]: Dialog \'{dialog_title}\' found in region {region}"'),
    ('f"  步骤 [{i:02d}]: 坐标轴出现数值 {target_value} (图像已放大)"',
     'f"  Step [{i:02d}]: Axis value {target_value} appeared (image zoomed in)"'),
    ('f"  步骤 [{i:02d}]: 坐标轴计数 = {binding_energy_count}, 期望 = {expected_total_count}"',
     'f"  Step [{i:02d}]: Axis count = {binding_energy_count}, expected = {expected_total_count}"'),
    ('f"  步骤 [{i:02d}]: 弹窗出现"',
     'f"  Step [{i:02d}]: Dialog appeared"'),
    ('f"  步骤 [{i:02d}]: 数量不匹配 (标题:{matched_count} vs 轴:{binding_energy_count})"',
     'f"  Step [{i:02d}]: Count mismatch (title:{matched_count} vs axis:{binding_energy_count})"'),
    ('f"  步骤 [{i:02d}]: 文件匹配但 Binding Energy 不足/过多"',
     'f"  Step [{i:02d}]: Files matched but Binding Energy count insufficient/excessive"'),
    ('f"  步骤 [{i:02d}]: 文件匹配成功 {list(matched_expectations)}，开始OCR检查Binding Energy..."',
     'f"  Step [{i:02d}]: Files matched {list(matched_expectations)}, starting OCR check for Binding Energy..."'),
    ('f"  步骤 [{i:02d}]: 标题数量已达标 ({matched_count})，正在校验坐标轴..."',
     'f"  Step [{i:02d}]: Title count reached ({matched_count}), verifying axis..."'),
    ('f"  规范化列表已设置，长度: {len(self.screenshot_files_normalized)}"',
     'f"  Normalized list set, length: {len(self.screenshot_files_normalized)}"'),
    ('f"  识别到的文件: {\', \'.join(sorted(all_detected_files))}"',
     'f"  Identified files: {\', \'.join(sorted(all_detected_files))}"'),
    ('f"  非空规范化变体样本: {non_none_normalized[:10]}"',
     'f"  Non-null normalized variant sample: {non_none_normalized[:10]}"'),
    ('f"  - \'{filename}\' 出现在步骤: {steps}"',
     'f"  - \'{filename}\' appears in steps: {steps}"'),
    ('f"  OCR预览: {preview}"', 'f"  OCR preview: {preview}"'),
    ('f"  尝试的标题变体: {title_variants}"', 'f"  Attempted title variants: {title_variants}"'),
    ('f"⚠️ 未找到评估函数: {func_name}"', 'f"⚠️ Evaluation function not found: {func_name}"'),
    # success/fail messages
    ('f"✓ 元素 \'{element_name}\' 出现 {count} 次 (截图{i})"',
     'f"✓ Element \'{element_name}\' appears {count} times (screenshot {i})"'),
    ('f"✓ 发现弹窗标题: {title} (截图{i})"',
     'f"✓ Dialog title found: {title} (screenshot {i})"'),
    ('f"✓ 发现网格布局设置: {rows}x{columns} (截图{i})"',
     'f"✓ Grid layout found: {rows}x{columns} (screenshot {i})"'),
    ('f"✓ 发现能量轴反向选项 (截图{i})"',
     'f"✓ Energy axis reversal option found (screenshot {i})"'),
    ('f"✓ 堆叠图切换成功 (步骤 {i})"', 'f"✓ Stacked graph switched successfully (step {i})"'),
    ('f"✓ 弹窗出现并关闭: 出现({result[\'details\'][\'appeared_at\']}) → 关闭({i})"',
     'f"✓ Dialog appeared and closed: appeared({result[\'details\'][\'appeared_at\']}) → closed({i})"'),
    ('f"✓ 成功: 在步骤 {i} 检测到所有文件且 Binding Energy 数量匹配"',
     'f"✓ Success: all files detected and Binding Energy count matched at step {i}"'),
    ('f"✓ 成功: 步骤 {i} 标题与坐标轴数量严格匹配 ({expected_total_count})"',
     'f"✓ Success: title and axis counts strictly matched at step {i} ({expected_total_count})"'),
    ('f"✓ 成功：完整检测到背景增加轨迹（打开-识别到{bg_type}-关闭）"',
     'f"✓ Success: full background addition trajectory detected (open - identified {bg_type} - close)"'),
    ('f"✓ 成功: 在步骤 {i} 检测到 {max_count} 个 {original_file} 副本"',
     'f"✓ Success: detected {max_count} copies of {original_file} at step {i}"'),
    ('f"✗ 图像放大后未恢复: 数值 \'{target_value}\' 未消失"',
     'f"✗ Image not restored after zoom: value \'{target_value}\' did not disappear"'),
    ('f"✗ 图像未进行放大操作: 未检测到数值 \'{target_value}\'"',
     'f"✗ Image zoom not performed: value \'{target_value}\' not detected"'),
    ('f"✗ 失败: 未找到完全满足条件的帧。最佳匹配在步骤 {best_step_details.get(\'step\')}，找到了 {len(best_step_details.get(\'found_files\'))}/{expected_count} 个文件。"',
     'f"✗ Fail: no frame fully satisfies conditions. Best match at step {best_step_details.get(\'step\')}, found {len(best_step_details.get(\'found_files\'))}/{expected_count} files."'),
    ('f"✗ 失败: 未检测到足够的文件副本"', 'f"✗ Fail: insufficient file copies detected"'),
    ('f"✗ 失败: 未能找到标题与坐标轴数量均为 {expected_total_count} 的截图"',
     'f"✗ Fail: no screenshot found with both title and axis count equal to {expected_total_count}"'),
    ('f"✗ 失败：大数值已消失，但未能在同一帧识别到至少两个小刻度 {small_values}"',
     'f"✗ Fail: large value disappeared but could not identify at least two small ticks {small_values} in same frame"'),
    ('f"✗ 失败：对话框已打开，但未能在其列表中识别到 \'{bg_type}\' (可能未点击Add或默认参数未生效)"',
     'f"✗ Fail: dialog opened but \'{bg_type}\' not identified in list (Add not clicked or default param not applied)"'),
    ('f"✗ 失败：未检测到对话框 \'{title}\'"', 'f"✗ Fail: dialog \'{title}\' not detected"'),
    ('f"✗ 失败：背景已识别，但对话框未检测到关闭动作"',
     'f"✗ Fail: background identified but dialog close action not detected"'),
    ('f"✗ 弹窗 \'{title}\' 出现但未关闭"', 'f"✗ Dialog \'{title}\' appeared but not closed"'),
    ('f"✗ 弹窗 \'{title}\' 未出现"', 'f"✗ Dialog \'{title}\' did not appear"'),
    ('f"✗ 未发现弹窗标题: {title}"', 'f"✗ Dialog title not found: {title}"'),
    ('f"✗ 未发现网格布局设置: {rows}x{columns}"', 'f"✗ Grid layout not found: {rows}x{columns}"'),
    ('f"✗ 未找到参数: {missing_params}"', 'f"✗ Parameters not found: {missing_params}"'),
    ('f"✗ 未找到弹窗: {dialog_title}"', 'f"✗ Dialog not found: {dialog_title}"'),
    ('f"开始深度检测背景操作：{title} -> {bg_type}"',
     'f"Starting deep background operation detection: {title} -> {bg_type}"'),
    ('f"检查弹窗参数: {dialog_title} - {dict(zip(parameter_name, expected_value))} (区域: {region})"',
     'f"Checking dialog params: {dialog_title} - {dict(zip(parameter_name, expected_value))} (region: {region})"'),
    ('f"检查弹窗参数名存在: {dialog_title} - {parameter_name} (区域: {region})"',
     'f"Checking dialog param name exists: {dialog_title} - {parameter_name} (region: {region})"'),
    ('f"检查弹窗是否存在: {dialog_title} (区域: {region})"',
     'f"Checking dialog exists: {dialog_title} (region: {region})"'),
    ('f"检查文件复制: {original_file} 应出现 {expected_copies} 次"',
     'f"Checking file copy: {original_file} should appear {expected_copies} times"'),
    ('f"检查元素数量增加: {element_name} -> {expected_count}个"',
     'f"Checking element count increase: {element_name} -> {expected_count}"'),
    ('f"检查图像放大缩小 (目标值: {target_value})"',
     'f"Checking image zoom (target value: {target_value})"'),
    ('f"检查多文件导入(单帧全满足): {\', \'.join(expected_files)}"',
     'f"Checking multi-file import (all in one frame): {\', \'.join(expected_files)}"'),
    ('f"检查弹窗出现并关闭: {title}"', 'f"Checking dialog appears and closes: {title}"'),
    ('f"检查弹窗标题: {title}"', 'f"Checking dialog title: {title}"'),
    ('f"检查网格布局: {rows}行 x {columns}列"', 'f"Checking grid layout: {rows} rows x {columns} columns"'),
    ('f"检查谱图复制(严格匹配): {\', \'.join(expected_files)}"',
     'f"Checking spectrum copy (strict match): {\', \'.join(expected_files)}"'),
    ('f"开始检测堆叠图：正则兼容模式"', 'f"Starting stacked graph detection: regex-compatible mode"'),
    ('f"检查能量轴反向"', 'f"Checking energy axis reversal"'),
    # docstring param descriptions (inline)
    ('region: 检测区域，默认为"full"', 'region: detection region, default "full"'),
    ("expected_files: 期望导入的文件名列表", "expected_files: list of expected filenames to import"),
    ("target_value: 目标数值（如 '282'）", "target_value: target value (e.g. '282')"),
    ("small_values: 堆叠图模式下出现的刻度 (如 ['2','4','6'])", "small_values: tick marks in stacked graph mode (e.g. ['2','4','6'])"),
    ("normal_markers: 传进来的旧参数（保持兼容，不报错，逻辑内会自动结合正则使用）",
     "normal_markers: legacy parameter passed in (kept for compatibility, combined with regex internally)"),
    ("dialog_title: 弹窗标题", "dialog_title: dialog title"),
    ("title: 弹窗标题", "title: dialog title"),
    ("element_name: 元素名称", "element_name: element name"),
    ("expected_count: 期望出现次数", "expected_count: expected occurrence count"),
    ("parameter_name: 原始参数名", "parameter_name: original parameter name"),
    ("parameter_name: 参数名称，可以是字符串或列表", "parameter_name: parameter name, can be string or list"),
    ("expected_value: 原始期望值", "expected_value: original expected value"),
    ("expected_value: 期望值，可以是字符串、列表或None（None表示只检查参数名存在）",
     "expected_value: expected value, can be string, list, or None (None means only check parameter name exists)"),
    ("task_name: 任务名称", "task_name: task name"),
    ("text: 原始OCR文本", "text: original OCR text"),
    ("normalized_text: 规范化后的OCR文本", "normalized_text: normalized OCR text"),
    ("normalized_text: 规范化后的文本（小写、无空格）", "normalized_text: normalized text (lowercase, no spaces)"),
    ("standard_filename: 标准文件名（如 'C1s Scan'）", "standard_filename: standard filename (e.g. 'C1s Scan')"),
    ("expected_normalized: 期望的规范化文件名（如 'c1sscan'）",
     "expected_normalized: expected normalized filename (e.g. 'c1sscan')"),
    ("detected_normalized: 检测到的规范化文件名（如 'cisscan'）",
     "detected_normalized: detected normalized filename (e.g. 'cisscan')"),
    ("checks: 检查项列表", "checks: list of check items"),
    ("columns: 列数", "columns: number of columns"),
    ("rows: 行数", "rows: number of rows"),
    ("'best_step_match': None,  # 记录匹配度最好的一次，用于调试",
     "'best_step_match': None,  # Record the best match for debugging"),
    ("continue # 当前是大数值帧，跳过，去找消失后的那一帧",
     "continue # Current frame has large values; skip and look for the frame after disappearance"),
    # return type descriptions
    ("评测结果字典", "evaluation result dict"),
    ("评估结果", "evaluation result"),
    ("识别出的文件名列表", "list of identified filenames"),
    ("变体列表", "variant list"),
    ("所有可能的变体列表", "list of all possible variants"),
    ("是否匹配", "whether matched"),
    ("匹配到的规范化变体（如 'cisscan'）", "matched normalized variant (e.g. 'cisscan')"),
    # inline comments in code lines
    ('"imported_files": ["C1s Scan", "C1s Scan"],  # 原始+复制',
     '"imported_files": ["C1s Scan", "C1s Scan"],  # original + copy'),
    ('"other_files": [],  # 如果这个任务打开了多个文件，在这里添加',
     '"other_files": [],  # Add here if other files were opened during this task'),
    ('"space_group_5_c2",  # 修正: "5 C2" 表示空间群的完整名称',
     '"space_group_5_c2",  # Note: "5 C2" is the full name of the space group'),
    ('"80l", # 带光标', '"80l", # with cursor'),
    ('"8O",  # O 代替 0', '"8O",  # O instead of 0'),
    ('"B0",  # B 代替 8', '"B0",  # B instead of 8'),
    ('"BO",  # 都错', '"BO",  # both wrong'),
    ('"peq", # 实际看到的误识别', '"peq", # actual misrecognition observed'),
    ('"brightness_0.3",               # 设置 Brightness = 0.3',
     '"brightness_0.3",               # Set Brightness = 0.3'),
    ('"contrast_0.2"                  # 设置 Contrast = 0.2',
     '"contrast_0.2"                  # Set Contrast = 0.2'),
    ('"dialog_image_display_info",    # 打开 Image Display Info 对话框',
     '"dialog_image_display_info",    # Open Image Display Info dialog'),
    ('"ifft_of_fft_of_dm9"    # 执行 IFFT',
     '"ifft_of_fft_of_dm9"    # Perform IFFT'),
    ('"文本颜色": [', '"text_color": ['),
    ('"框颜色": [', '"border_color": ['),
    # misc remaining
    ('self._log("✗ 失败: 未能匹配到任何期望文件。", "FAIL")',
     'self._log("✗ Fail: could not match any expected files.", "FAIL")'),
    ('self._log("✗ 失败：未检测到初始大数值状态（C1s 整数或 O1s 科学计数法）", "FAIL")',
     'self._log("✗ Fail: initial large-value state not detected (C1s integer or O1s scientific notation)", "FAIL")'),
    ('self._log("✗ 未发现能量轴反向选项", "FAIL")',
     'self._log("✗ Energy axis reversal option not found", "FAIL")'),
    # vesta evaluator specific
    ('top = int(height * 0.1)  # 去掉顶部10%', 'top = int(height * 0.1)  # Remove top 10%'),
    ('bottom = int(height * 0.8)  # 去掉底部20%', 'bottom = int(height * 0.8)  # Remove bottom 20%'),
    ('self._log(f"警告: 参考图片不存在: {ref_path}", "WARNING")',
     'self._log(f"Warning: reference image not found: {ref_path}", "WARNING")'),
    # Jade evaluator inline
    ("r'\\[([^\\]]*(?:XRD|xrd)[^\\]]*)\\]',  # 包含XRD的方括号内容",
     "r'\\[([^\\]]*(?:XRD|xrd)[^\\]]*)\\]',  # bracket content containing XRD"),
    ("r'\\[([^\\]]*(?:WRT|wrt)[^\\]]*)\\]',  # 包含WRT的方括号内容",
     "r'\\[([^\\]]*(?:WRT|wrt)[^\\]]*)\\]',  # bracket content containing WRT"),
    ('# 文件名通常在标题栏的方括号中，如 [XRD1.xrdml] 或 [WRT-ZSX-5.txt]',
     '# Filename is usually in title bar brackets, e.g. [XRD1.xrdml] or [WRT-ZSX-5.txt]'),
    ('# 先在规范化文本中搜索', '# First search in normalized text'),
    # ms evaluator specific
    ('elif region == "左侧30%":', 'elif region == "left30%":'),
    ('elif region == "右侧30%":', 'elif region == "right30%":'),
    ('elif region == "中心区域":', 'elif region == "center-area":'),
    ('elif region == "底部50%":', 'elif region == "bottom50%":'),
    ('elif region == "中心":', 'elif region == "center":'),
    ('elif region == "右下角":', 'elif region == "bottom-right":'),
    ('elif region == "左侧50%":', 'elif region == "left50%":'),
    ('# 缓存结果', '# Cache result'),
    ('"""预处理:识别所有截图中的信息(文件名、窗口标题等)"""',
     '"""Preprocessing: identify info in all screenshots (filenames, window titles, etc.)"""'),
    # test file specific
    ('规范化文件名，去除扩展名和多余字符', 'Normalize filename, remove extension and extra characters'),
    ('参数:', 'Args:'),
    ('filename: 原始文件名', 'filename: original filename'),
    ('返回:', 'Returns:'),
    ('规范化后的文件名（无扩展名）', 'normalized filename (without extension)'),
    ('计算单个检查点的理论得分 (修复版)', 'Calculate theoretical score for a single checkpoint (Fixed)'),
    ('1. check_field_value: 修复 field_name=None 时的数值匹配',
     '1. check_field_value: fix numeric matching when field_name=None'),
    ('2. check_text_keyword: 增强 opened_file 的匹配逻辑',
     '2. check_text_keyword: enhanced matching logic for opened_file'),
    ('计算单个检查点的理论得分', 'Calculate theoretical score for a single checkpoint'),
    ('VESTA 批量评估系统', 'VESTA Batch Evaluation System'),
    # dm_evaluate_test.py specific
    ('# # 方法2: 子串匹配 (检查value是否出现在任何operation中)',
     '# # Method 2: substring matching (check if value appears in any operation)'),
]


def apply_replacements(text: str) -> str:
    # Sort by length descending to avoid partial replacement issues
    for zh, en in sorted(REPLACEMENTS, key=lambda x: -len(x[0])):
        text = text.replace(zh, en)
    return text


FILES = [
    'avantage_evaluator.py',
    'dm_evaluator.py',
    'jade_evaluator.py',
    'ms_evaluator.py',
    'vesta_evaluator.py',
    'avantage_evaluate_test.py',
    'Jade_evaluate_test.py',
    'ms_evaluate_test.py',
    'dm_evaluate_test.py',
    'vesta_evaluate_test.py',
]

if __name__ == '__main__':
    for fname in FILES:
        fpath = BASE / fname
        if not fpath.exists():
            print(f"  SKIP {fname} (not found)")
            continue
        text = fpath.read_text(encoding='utf-8')
        new_text = apply_replacements(text)
        if new_text != text:
            fpath.write_text(new_text, encoding='utf-8')
            print(f"✓ Updated {fname}")
        else:
            print(f"  No changes: {fname}")
    print("\nDone!")
